Parametrise PParams by era
IntersectMBO/cardano-ledger pull request #1846
Opened 2020-09-08 21:15 UTC by polinavino

Parametrise PParams by era  - because in future eras, PParams will change
Parametrise everything else related to PParams that was needed for this to compile

2020-09-09 06:38 UTC, mrBliss commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Genesis.hs
> +    sgProtocolParams :: !(PParams c),
The `c` should be renamed to `era` (before this PR).

2020-09-09 06:38 UTC, mrBliss commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/PParams.hs
> +type PParams e = PParams' Identity e
Let's stick to `era` instead of `e`.

2020-09-09 06:38 UTC, mrBliss commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Delegs.hs
> +    delegspp :: (PParams era),
These parenthesis are redundant (same for the line below), I suspect a result of using find & replace.

2020-09-09 07:08 UTC, nc6 requested changes
Requesting the changes that @mrBliss suggested

2020-09-10 07:08 UTC, nc6 approved these changes

2020-09-10 07:08 UTC, merged