Adding pphash and making hash to data map
IntersectMBO/cardano-ledger pull request #2067
Opened 2020-12-17 19:38 UTC by polinavino

This PR 
- adds the PP hash to `TxBody`
- changes the `Data` set in `TxWitness` to a hash-indexed map

2021-01-05 16:12 UTC, nc6 requested changes
Couple of changes, otherwise looks good.

2021-01-05 16:12 UTC, nc6 commented on alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs
> +newtype PPHash crypto
Please add this to a new module (maybe `Cardano.Ledger.Alonzo.ProtocolParameters`) rather than adding it to `TxBody`.

2021-01-05 16:12 UTC, nc6 commented on alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs
> +      Rec @(CompactAddr (Crypto era) -> CompactForm (Core.Value era) -> StrictMaybe (DataHash (Crypto era)) -> TxOut era)
Is this change really needed? I can't see anything in this PR which would precipitate it?

2021-01-05 16:12 UTC, nc6 commented on alonzo/impl/test/lib/Test/Cardano/Ledger/Alonzo/Serialisation/Generators.hs
> +  ( ShelleyBased era,
We're trying to deprecate the various `ShelleyBased` constraints, so you should use the various `UseFoo` constraints as needed.

2021-01-05 16:28 UTC, polinavino commented on alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs
> +newtype PPHash crypto
There is already a `PParams` module in Alonzo, ok if I put it there?

2021-01-05 19:31 UTC, polinavino commented on alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs
> +      Rec @(CompactAddr (Crypto era) -> CompactForm (Core.Value era) -> StrictMaybe (DataHash (Crypto era)) -> TxOut era)
changed the type application to CompactTxOut @era instead

2021-01-06 08:53 UTC, nc6 commented on alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs
> +newtype PPHash crypto
Ah, indeed, perfect!

2021-01-06 08:55 UTC, nc6 approved these changes

2021-01-06 08:55 UTC, merged