Added deserialisation tests for length-of Plutus ByteStrings > 64.
IntersectMBO/cardano-ledger pull request #2216
Opened 2021-04-01 18:01 UTC by TimSheard

In order to validate data in both AuxiliaryData and in the WitnessSet, deserializing
a Plutus Data, with a ByteString type, whose length is greater than 64 now raises
a deserialisation error. Added a new combinator (<?) to Data.Coders that lets any
'constructor' raise an error. Also added roundtrip tests to be sure we actually
catch these cases.

2021-04-01 18:14 UTC, JaredCorduan approved these changes
If we can add the `FromCBOR (Annotator (Data era))` back in, I think it looks great!

2021-04-12 11:46 UTC, nc6 requested changes
Shouldn't add additional consttaints on the API types, otherwise looks fine.

2021-04-13 21:24 UTC, TimSheard commented
I cleaned this up, addressed the (Show(CompactAddr era)) comments from Nick, rebased on the most recent master.
I am still getting a serialisation error in the benchmarks.

bench: Failed to decode state: DecoderErrorDeserialiseFailure "state" (DeserialiseFailure 6689 "expected integer")
CallStack (from HasCallStack):
  error, called at bench/Bench/Cardano/Ledger/ApplyTx.hs:100:25 in main:Bench.Cardano.Ledger.ApplyTx
Benchmark bench: ERROR
cabal: Benchmarks failed for bench:bench from cardano-ledger-test-0.1.0.0.

2021-04-20 09:15 UTC, nc6 approved these changes

2021-04-20 09:15 UTC, merged