RetiredPools event
IntersectMBO/cardano-ledger pull request #2487
Opened 2021-09-16 21:44 UTC by goolord

2021-09-16 21:52 UTC, JaredCorduan approved these changes
Looks good to me! Out of curiosity, the type annotations were not necessary, right? just for clarity?

2021-09-16 21:54 UTC, goolord commented
yes, it was just to help me grok this

2021-09-16 22:02 UTC, nc6 requested changes, later dismissed
I don't think this has the needed information. Having `refunds` and `mRefunds` would I think be more useful, since these associate with the accounts they are paid to. Even better would be something like
```
refunds :: Map (Credential 'Staking crypto) (Map (KeyHash 'StakePool crypto) Coin)
```

This would allow DB-sync to recreate all the needed information

2021-09-16 22:02 UTC, nc6 commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs
> +  { refundPools :: Map.Map (KeyHash 'StakePool (Crypto era)) Coin,
I don't believe this has the information we need, since this doesn't identify _who_ will be credited with the rewards

2021-09-16 22:34 UTC, JaredCorduan commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs
> +  { refundPools :: Map.Map (KeyHash 'StakePool (Crypto era)) Coin,
does @erikd want the reward account, and not the stake pool id?

2021-09-16 23:36 UTC, lehins commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs
> +          }
Just a minor suggestion, let bindings seem superfluous:
```suggestion
     RetiredPools
        { refundPools = Map.mapMaybe (\ra -> Map.lookup (getRwdCred ra) refunds) rewardAcnts
          unclaimedPools = Map.mapMaybe (\ra -> Map.lookup (getRwdCred ra) mRefunds) rewardAcnts
        }
```

2021-09-16 23:44 UTC, goolord commented
ok, refunds and unclaimed are supplied as `Map.Map (Credential 'Staking (Crypto era)) (Map.Map (KeyHash 'StakePool (Crypto era)) Coin)` now

2021-09-17 02:11 UTC, merged

2021-09-17 14:25 UTC, goolord commented on shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs
> +            rewardAcntsWithPool
pretty sure this is at least an order of magnitude slower than it needs to be, but it was the easiest way for my fried brain to reason about constructing this at the time. might be worth revisiting later : )