parameterize Block by the header type
IntersectMBO/cardano-ledger pull request #2510
Opened 2021-10-05 21:42 UTC by JaredCorduan

This changes the `Block` type to be parameterized by the block header type. I did not attempt to make the tests more generic, but just used the TPraos `BHeader` directly.

closes #2459

2021-10-06 06:00 UTC, nc6 requested changes
This looks great, but now that `Block` is parametrised by the header, can we revert to using `Block` as the signal for `BBODY` rather than the tuple?

2021-10-06 06:00 UTC, nc6 commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/BlockChain.hs
> +data Block h era
Now that `Block` is parametric over the header type, I wonder whether we should move it to `cardano-ledger-core`

2021-10-06 13:58 UTC, JaredCorduan commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/BlockChain.hs
> +data Block h era
These are some great ideas, thanks @nc6 ! I'll do some experimenting. :scientist:

2021-10-08 21:29 UTC, JaredCorduan commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/BlockChain.hs
> +data Block h era
@nc6 this turned out mostly great, see my notes in the PR notes at the top.

2021-10-11 07:32 UTC, nc6 requested changes
Looks great, I think the changes make this much nicer! I have left one final suggestion. Also, is this file intentionally checked in?
- eras/shelley/impl/dist/cabal-config-flags

2021-10-11 07:32 UTC, nc6 commented on libs/cardano-ledger-core/src/Cardano/Ledger/Block.hs
> +  = Block' !(h (Crypto era)) !(Era.TxSeq era) BSL.ByteString
Rather than exposing the constructor directly, how about having a pair of patterns which we use in cases where we don't care about serialisation: a unidirectional pattern `UnserialisedBlock` that allows us to pull out the header and the TxSeq, and a bidirectional `UnsafeUnserialisedBlock` which constructs the block with an error in the bytestring? This way it's a bit clearer what's going on, and we don't have to expose the potentially unsafe constructor?

2021-10-11 12:07 UTC, JaredCorduan commented on libs/cardano-ledger-core/src/Cardano/Ledger/Block.hs
> +  = Block' !(h (Crypto era)) !(Era.TxSeq era) BSL.ByteString
Absolutely, that's much better!

2021-10-11 12:33 UTC, JaredCorduan commented
> Looks great, I think the changes make this much nicer! I have left one final suggestion. Also, is this file intentionally checked in?
> 
> * eras/shelley/impl/dist/cabal-config-flags

oops! I'll remove it, thanks! Edit: done.

2021-10-12 07:10 UTC, nc6 approved these changes

2021-10-12 07:10 UTC, merged