Lehins ts/split libs
IntersectMBO/cardano-ledger pull request #2582
Opened 2021-12-08 18:14 UTC by TimSheard

Split small-steps into three parts
  small-steps (Control.State.Transition, Control.State.Transition.Extended, ...)
  cardano-data  (Data.Coders, Data.MemoBytes, Data.BiMap, Data.Sharing ...)
  set-algebra (Control.Iterate.BaseTypes, Control.Iterate.SetAlgebra, ...)

This makes it possible for set-algebra to depend on cardano-ledger-core, this supports Set Algebra expression over types that know about Core types.

2021-12-08 18:28 UTC, lehins requested changes
We forgot couple of renames and also I forgot to mention that we need to add these two settings intro the top level `cabal.project` in order to turn warnings into errors:

```
package set-algebra
  ghc-options: -Werror

package cardano-data
  ghc-options: -Werror
```


And of course it needs a rebase on master

2021-12-08 18:28 UTC, lehins commented on libs/cardano-data/default.nix
> +  pkgs.libs.small-steps
Looks like we missed some
```suggestion
  pkgs.libs.cardano-data
```

2021-12-08 18:28 UTC, lehins commented on libs/set-algebra/CHANGELOG.md
> +# Revision history for small-steps
```suggestion
# Revision history for set-algebra
```

2021-12-08 18:28 UTC, lehins commented on libs/set-algebra/default.nix
> +  pkgs.libs.small-steps
```suggestion
  pkgs.libs.set-algebra
```

2021-12-08 18:28 UTC, lehins commented on libs/cardano-data/CHANGELOG.md
> +# Revision history for small-steps
```suggestion
# Revision history for cardano-data
```

2021-12-08 18:57 UTC, TimSheard commented on libs/cardano-data/default.nix
> +  pkgs.libs.small-steps
done

2021-12-08 18:57 UTC, TimSheard commented on libs/set-algebra/CHANGELOG.md
> +# Revision history for small-steps
done

2021-12-08 18:57 UTC, TimSheard commented on libs/set-algebra/default.nix
> +  pkgs.libs.small-steps
done

2021-12-08 18:57 UTC, TimSheard commented on libs/cardano-data/CHANGELOG.md
> +# Revision history for small-steps
done

2021-12-09 13:37 UTC, JaredCorduan approved these changes
thanks @TimSheard !

2021-12-09 14:34 UTC, lehins approved these changes

2021-12-09 14:34 UTC, merged