weaken `FromCBOR` for `TxOut` to `Annotator TxOut`
IntersectMBO/cardano-ledger pull request #2593
Opened 2021-12-22 16:16 UTC by goolord

required for https://github.com/input-output-hk/cardano-ledger/pull/2560

babbage's `TxOut` will only be an instance of `FromCBOR (Annotator TxOut)`, so this pr adds instances for `FromCBOR (Annotator..` as it bubbles up from `TxOut` and weakens those constraints where necessary in code that's reused in babbage

2021-12-23 16:25 UTC, lehins requested changes
I highly recommend avoiding all the copy pasting. Most of the code added in this PR can be avoided. For example:

```haskell
instance ... => FromCBOR (Annotator (EpochState era)) where
  fromCBOR = do
    es@EpochState {eslState} <- fromCBOR
    pure $ Annotator $ \fbs -> es {esLState = runAnnotator esLState fbs}
```

It is especially dangerous to copy serialization/deserialziation code like that, because it s possible that someone in the future will change one `fromCBOR`, but not the other other one.

Also it is very bad practice to copy paste code in general, it is almost always better to create an abstraction. A professor of mine said once: "If you are finding yourself copying a piece of code, it is most likely that you are doing something wrong." 

So please, keep your code as [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) as possible.

2021-12-25 18:13 UTC, goolord commented
I don't think the code in your example would typecheck. since the constraints are different the instances have to be duplicated, or we can remove the non-Annotator FromCBOR instances, but not both

2021-12-25 18:35 UTC, goolord commented
i think i have a couple of ideas wrt getting code reuse here actually, I'll try them out after Christmas ⛄🎄

2021-12-26 08:16 UTC, goolord commented
actually, I just realized that if `Ann` and `ApplyAnn` are generalized to `Applicative`, all of these instances can share the same decoding function, so i'm going to do that

2022-01-03 18:10 UTC, JaredCorduan approved these changes
Adding those annotators do tend to infect a lot of code, thanks for plowing through this! LGTM

2022-01-03 21:06 UTC, lehins approved these changes
This looks great. @goolord thank you for reducing duplication!

There are just a couple of minor suggestions that I have in this review.

2022-01-03 21:06 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState.hs
> +    -- Share (f (Core.TxOut era)) ~ Interns (Credential 'Staking (Crypto era)),
```suggestion
```

2022-01-03 21:06 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState.hs
> +      Interns (Credential 'Staking (Crypto era))
I think it would be more appropriate to use UTXOState, but it would not be incorrect to leave it as it is right now too. So feel free to ignore this suggestion if you'd like
```suggestion
    Share (Annotator (UTxOState era)) = Share (UTxOState era)
```

2022-01-04 00:02 UTC, merged