minor babbage cleanup
IntersectMBO/cardano-ledger pull request #2638
Opened 2022-01-27 21:06 UTC by JaredCorduan

Two small things here (each in separate commit):
* Use a new function, `hasTxIn` to make clear how a script purpose can be a transaction input
* In the `feesOk` function, a transaction was used in a few spots that actually needed a transaction body

2022-01-27 21:06 UTC, JaredCorduan commented on eras/babbage/formal-spec/transactions.tex
> +      \ScriptPurpose & \PolicyID \uniondistinct \TxIn \uniondistinct \AddrRWD \uniondistinct \DCert
@TimSheard was adamant that I remind the reader here what a `ScriptPurpose` was, even though it has not changed :)

2022-02-10 23:08 UTC, nc6 requested changes

2022-02-10 23:08 UTC, nc6 commented on eras/babbage/formal-spec/utxo.tex
> +        [\var{d}] & \var{txin}\in_?(\fun{hasTxIn}~\var{sp}),   (\_, \_, h, \_) \in \var{utxo}~\var{txin},~ \var{d} \in \Datum \\
I'm struggling to follow this. `\in_?` is undefined, which doesn't help, but also - what is `txin`? It seems to accept `utxo` as a function, but `utxo` is of type `\UTxO`, right?

2022-02-10 23:29 UTC, JaredCorduan commented on eras/babbage/formal-spec/utxo.tex
> +        [\var{d}] & \var{txin}\in_?(\fun{hasTxIn}~\var{sp}),   (\_, \_, h, \_) \in \var{utxo}~\var{txin},~ \var{d} \in \Datum \\
yep, this is still confusing and wrong, I will fix it up!

2022-02-11 11:39 UTC, WhatisRT commented on eras/babbage/formal-spec/utxo.tex
> +        [\var{d}] & \var{txin}\in_?(\fun{hasTxIn}~\var{sp}),   (\_, \_, h, \_) \in \var{utxo}~\var{txin},~ \var{d} \in \Datum \\
I think this `hasTxIn` thing is a bad idea. Just say `sp \in \TxIn` to give the extra information

2022-02-17 18:22 UTC, JaredCorduan commented
I'm going to close this PR for now and let @WhatisRT incorporate whichever of the ideas here that he likes into any subsequent additions to the babbage spec. :)

2022-02-17 18:22 UTC, closed without merging