Refactor - break LedgerState into smaller modules
IntersectMBO/cardano-ledger pull request #2894
Opened 2022-07-01 17:19 UTC by Soupstraw

2022-07-01 19:06 UTC, lehins requested changes
I did a quick skim through the PR and it overall looks pretty good. I made couple of comments on the re-exporting.

<strike> Also I do like having some visualizations and stuff, however they are bound to get outdated over time. So I don't think it is a good idea to add this image into the repo: `libs/cardano-ledger-core/modules.png-1.png` The only way we could add such graphs to the repo if we have a CI action that validates they did not go out of sync together with a clear readme section on how to regenerate them when they do.</strike> I saw that you removed it :smile:, but it was only after I submitted the review

One more important point. I am sure you know this, but just to be safe I'd like to mention it anyways, make sure you don't add any semantic changes in this PR, since in refactorings like that it is hard to notice any changes to the logic implemented in functions.

2022-07-01 19:06 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState.hs
> -  ( AccountState (..),
In order to reduce breakage downstream we still need to make sure we export everything from the LedgerState module that we exported before.

2022-07-01 19:06 UTC, lehins commented on eras/shelley/impl/cardano-ledger-shelley.cabal
> +    Cardano.Ledger.Shelley.LedgerState.IncrementalStake
Maybe it is better to make those modules internal and let everything LedgerState related be exported from `Cardano.Ledger.Shelley.LedgerState`, just as it was before.

Less modules for public to deal with is better.

2022-07-01 20:00 UTC, JaredCorduan commented
Note that this PR closes  #1675

2022-07-05 12:56 UTC, Soupstraw commented on eras/shelley/impl/cardano-ledger-shelley.cabal
> +    Cardano.Ledger.Shelley.LedgerState.IncrementalStake
Done, moved the submodules to the `other-modules` section.

2022-07-05 14:48 UTC, JaredCorduan approved these changes
I really like all these changes!

2022-07-05 15:14 UTC, Soupstraw commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState.hs
> -  ( AccountState (..),
Done, and I added deprecated functions and a type synonym for WitHashes.

2022-07-05 20:18 UTC, lehins approved these changes
Looks awesome. Love this cleanup

2022-07-05 20:18 UTC, merged