update readme with new nix substituters
IntersectMBO/cardano-ledger pull request #2973
Opened 2022-08-11 01:02 UTC by JaredCorduan

2022-08-15 16:17 UTC, lehins commented
Related to this. NixOS has deprecated `nix.binaryCaches` and`nix.binaryCachePublicKeys`, so we should update the NixOS settings too:

```nix
  nix.settings = {
    substituters = [
      "https://cache.iog.org"
      "https://hydra.iohk.io"
    ];
    trusted-public-keys = [
      "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="
    ];
  };
```

2022-08-15 17:22 UTC, JaredCorduan commented
> ```nix
> cache.iog.org
> ```

I think you meant `cache.iog.io`.

2022-08-15 17:45 UTC, lehins commented
> I think you meant cache.iog.io.

:smile: Yeah, that's exactly what I meant. I update a part of the wrong url :man_facepalming:

2022-08-15 18:17 UTC, lehins commented
Does the key needs to be updated too?
```diff
-trusted-public-keys = hydra.iohk.io
+trusted-public-keys = cache.iog.io
```

2022-08-16 11:58 UTC, JaredCorduan commented
> Does the key needs to be updated too?
> 
> ```diff
> -trusted-public-keys = hydra.iohk.io:f/Ea+s+...
> +trusted-public-keys = cache.iog.io:f/Ea+s+...
> ```

I believe that @disassembler told me that they do not.

2022-08-16 12:01 UTC, michaelpj approved these changes
Looks right!

2022-08-16 12:03 UTC, lehins approved these changes

2022-08-16 13:41 UTC, disassembler requested changes
Some suggestions to add flakes and not support config in home directory

2022-08-16 13:41 UTC, disassembler commented on README.md
> +  substituters = [
```suggestion
  experimental-features = [ "nix-command" "flakes" ];
  substituters = [
```

2022-08-16 13:41 UTC, disassembler commented on README.md
> +substituters        = https://cache.iog.io https://cache.nixos.org/
```suggestion
experimental-features = nix-command flakes
substituters        = https://cache.iog.io https://cache.nixos.org/
```

2022-08-16 13:41 UTC, disassembler commented on README.md
>  the following in `/etc/nix/nix.conf` if you have a system-wide `nix`
```suggestion
the following in `/etc/nix/nix.conf`:
```

2022-08-16 13:41 UTC, disassembler commented on README.md
>  installation , or in `~/.config/nix/nix.conf` if you have a local installation:
```suggestion
```

2022-08-16 14:07 UTC, JaredCorduan commented
thank you for the suggestions @disassembler !

2022-08-17 21:23 UTC, disassembler approved these changes

2022-08-17 21:23 UTC, disassembler commented
bors r+

2022-08-18 17:07 UTC, merged