Update plutus version
IntersectMBO/cardano-ledger pull request #3030
Opened 2022-09-08 16:59 UTC by teodanciu

2022-09-14 14:52 UTC, Unisay commented
FYI: https://github.com/kapralVV/Unique/pull/10

2022-09-17 12:12 UTC, lehins requested changes
I'll close this PR, since I've incorporated it into #2992

2022-09-17 12:12 UTC, lehins commented on eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs
> +  PlutusScript PlutusV2 bytes -> (not . null) (PV2.assertScriptWellFormed (transProtocolVersion pv) bytes :: Either ScriptDecodeError ())
It is better to use specialized function `isRight` instead of relying on Foldable instance for Either:

2022-09-17 21:23 UTC, lehins commented
Closed it in favor of #2992

2022-09-17 21:23 UTC, closed without merging

2022-09-20 13:10 UTC, teodanciu commented
Nice, thank you for making something usable from two partial things!