move RewardType and Reward to cardano-ledger-core package
IntersectMBO/cardano-ledger pull request #3059
Opened 2022-09-29 16:52 UTC by JaredCorduan

I moved the `RewardType` and `Reward` types from the `Cardano.Ledger.Shelley.Reward` module in the `cardano-ledger-shelley` package into a new module `Cardano.Ledger.Reward` in the `cardano-ledger-core` package. And added a wee bit of documentation while I was at it.

2022-10-03 12:35 UTC, lehins requested changes
I am not really sure what is the motivation behind moving Reward into Core, but I don't think it hurts anyone either. We definitely don't need to add any deprecations. There is nothing wrong with re-exporting types from another module

2022-10-03 12:35 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rewards.hs
> +    Reward,
This will only introduce unnecessary breakage downstream it is better to just re-export those types from here.

2022-10-03 12:35 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/Rewards.hs
> +  compare (Reward _ pool1 _) (Reward _ pool2 _) = compare pool1 pool2
Oh crap. Not another one. I created a ticket for it: https://github.com/input-output-hk/cardano-ledger/issues/3060

2022-10-07 11:26 UTC, lehins approved these changes
LGTM

2022-10-07 11:26 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/Rewards.hs
> +-- * leader rewards - rewards given to a registered stake pool (in particular, given to to the
```suggestion
-- * leader rewards - rewards given to a registered stake pool (in particular, given to the
```

2022-10-07 11:48 UTC, JaredCorduan commented on libs/cardano-ledger-core/src/Cardano/Ledger/Rewards.hs
> +-- * leader rewards - rewards given to a registered stake pool (in particular, given to to the
given :tutu:

2022-10-07 20:43 UTC, merged