Refactor `delegationTransition`
IntersectMBO/cardano-ledger pull request #3129
Opened 2022-11-08 14:41 UTC by WhatisRT

There was a lot of code copy which was in the way of @teodanciu and me figuring out what changes if `allowMIRTransfer` is true or not. We took this as an opportunity for some refactoring.

2022-11-08 15:34 UTC, lehins requested changes
Love the deduplication. :heart: Suggested even further improvement

2022-11-08 15:34 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +        (SendToOppositePotMIR coin) ->
Redundant parenthesis
```suggestion
        SendToOppositePotMIR coin ->
```

2022-11-08 15:34 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +        (StakeAddressesMIR credCoinMap) -> do
Redundant parenthesis
```suggestion
        StakeAddressesMIR credCoinMap -> do
```

2022-11-08 15:34 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +                      combinedMap = Map.union credCoinMap' instantaneousRewards
Here is some more deduplication (also removes a few lines from below, just can't add this as suggestion). Note that `delta` is computed lazily:
```suggestion
          let (potAmount, delta, instantaneousRewards) =
                case targetPot of
                  ReservesMIR -> (asReserves acnt, deltaReserves $ dsIRewards ds, iRReserves $ dsIRewards ds)
                  TreasuryMIR -> (asTreasury acnt, deltaTreasury $ dsIRewards ds, iRTreasury $ dsIRewards ds)
              credCoinMap' = Map.map (\(DeltaCoin x) -> Coin x) credCoinMap

          (requiredForRewards, available) <- if HardForks.allowMIRTransfer pp
            then do
              let combinedMap = Map.unionWith (<>) credCoinMap' instantaneousRewards
              all (>= mempty) combinedMap ?! MIRProducesNegativeUpdate
              pure (fold combinedMap, potAmount `addDeltaCoin` delta)
            else do
              let combinedMap = Map.union credCoinMap' instantaneousRewards
              all (>= mempty) credCoinMap ?! MIRNegativesNotCurrentlyAllowed
              pure (fold combinedMap, potAmount)
                      
```

2022-11-08 15:34 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +                ?! MIRNegativeTransfer targetPot coin
Let's put it on one line, it's not that long and will improve redability
```suggestion
              coin >= mempty ?! MIRNegativeTransfer targetPot coin
```

2022-11-08 15:34 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +                ?! InsufficientForTransferDELEG targetPot coin available
Same here:
```suggestion
              coin <= available ?! InsufficientForTransferDELEG targetPot coin available
```

2022-11-08 15:34 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +        ?! MIRCertificateTooLateinEpochDELEG slot tooLate
Same here:
```suggestion
      slot < tooLate ?! MIRCertificateTooLateinEpochDELEG slot tooLate
```

2022-11-08 18:01 UTC, teodanciu commented
I'll make this work and adapt the suggestions when I'm back on Friday!

2022-11-17 12:34 UTC, JaredCorduan approved these changes
great cleanup, thank you @teodanciu !

The darwin cicero build is failing with something I don't understand:

```
F copying 2 paths...
F cardano-protocol-tpraos-lib-cardano-protocol-tpraos> Connection to 10.10.0.2 closed by remote host
F error: unexpected end-of-file
```

2022-11-23 19:00 UTC, lehins approved these changes
Thank you for reducing duplication. Great stuff!!

Just one minor stylistic comment

2022-11-23 19:00 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +  do
For consistency sake let's keep the `do` on the same line as the equal sign. This is the style used throughout the repo and I'd like to avoid mixing multiple styles.
```suggestion
checkSlotNotTooLate slot = do
```

2022-11-23 19:00 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Deleg.hs
> +  do
Same here
```suggestion
updateReservesAndTreasury targetPot combinedMap available ds = do
```

2022-11-25 10:22 UTC, merged