Add CDDL proptests for Conway
IntersectMBO/cardano-ledger pull request #3226
Opened 2022-12-28 11:25 UTC by aniketd

# Description

Add your description here, if it fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense
- [ ] Commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the [changelog](https://github.com/input-output-hk/cardano-ledger/blob/master/CHANGELOG.md)
- [ ] Code is formatted with ormolu (which can be run with `scripts/ormolise.sh`
- [ ] Self-reviewed the diff

2023-01-03 18:30 UTC, JaredCorduan commented on CHANGELOG.md
> +- Add CDDL proptests for Conway. #3226
thank you for remembering the changelog! test, however, do not need mention, though, so no need to update the changelog for this PR.

2023-01-03 18:33 UTC, JaredCorduan approved these changes
looks great! thank you for fixing up the conway serialization code, and making the CDDL file look nice along the way!

2023-01-03 19:18 UTC, aniketd commented on CHANGELOG.md
> +- Add CDDL proptests for Conway. #3226
Got you! Removing it!

2023-01-04 10:33 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoterRole) && n <= fromEnum (maxBound :: VoterRole)
Maybe this could be extracted to a top-level function in some utility module? Seems like something we might want to use in many places. It could be called `safeToEnum` for example.

2023-01-04 10:37 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoteDecision) && n <= fromEnum (maxBound :: VoteDecision)
And this could be replaced by `safeToEnum` to reduce code duplication.

2023-01-04 11:04 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoterRole) && n <= fromEnum (maxBound :: VoterRole)
Idea is great, but `safeToEnum` is an inconsistent name.

This function should go into `Cardano.Ledger.Binary.Decoding.Decoder` and should be called `decodeEnumBounded`:
```haskell
decodeEnumBounded :: forall a. (Enum a, Bounded a) => Decoder s a
    n <- decodeInt
    if n >= fromEnum (minBound :: a) && n <= fromEnum (maxBound :: a)
      then pura $ toEnum n
      else fail $ "Failed to decode an Enum: " ++ show n
```

2023-01-04 14:38 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoterRole) && n <= fromEnum (maxBound :: VoterRole)
Thanks @Soupstraw and @lehins :raised_hands: I looked for other examples of sum types that had simple data constructors of cardinality 1, and didn't find any. I have pushed the update. Let me know how you like it.

2023-01-04 14:41 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoteDecision) && n <= fromEnum (maxBound :: VoteDecision)
I didn't find it used in the repo, and I only found it in `relude`, which I didn't find being used in the repo as well. May be we can avoid adding it by compromising on the longer form `fromEnum` until we have too many instances of it?

2023-01-04 14:49 UTC, lehins requested changes
It is very unusual for `Cardano.Ledger.Binary.Coders` interface to need a change, so if you feel like you need to do that, more than likely you are doing something wrong.

Other than that it looks good.

FYI you could also use the new `decodeBoundedEnum` and `encodeEnum` for `To/FromCBOR` instances for `Language`

2023-01-04 14:49 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +  fromCBOR = decode EnumBoundedSumD
This should be
```suggestion
  fromCBOR = decodeEnumBounded
```

2023-01-04 14:49 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +  toCBOR = encode . EnumBoundedSum
This
```suggestion
  toCBOR = encodeEnum
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/Coders.hs
> +  EnumBoundedSumD :: (Enum t, Bounded t, Typeable t) => Decode 'Open t
This is not needed
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/Coders.hs
> +hsize EnumBoundedSumD = 0
That is not needed either
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Decoding/Coders.hs
> +decodeCount EnumBoundedSumD n = (n,) <$> decodeEnumBounded
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +  fromCBOR = decode EnumBoundedSumD
```suggestion
  fromCBOR = decodeEnumBounded
```

2023-01-04 14:49 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +  toCBOR = encode . EnumBoundedSum
```suggestion
  toCBOR = encodeEnum
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Coders.hs
> +encodeEnumBounded = encodeInt . fromEnum
Duplicate function
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Coders.hs
> +    encodeCountPrefix _ (EnumBoundedSum x) = encodeEnumBounded x
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Coders.hs
> +gsize (EnumBoundedSum _) = 0
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Coders.hs
> +runE (EnumBoundedSum cn) = cn
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Coders.hs
> +  EnumBoundedSum :: (Enum t, Bounded t) => t -> Encode 'Open t
```suggestion
```

2023-01-04 14:49 UTC, lehins commented on libs/cardano-ledger-binary/src/Cardano/Ledger/Binary/Encoding/Encoder.hs
> +encodeEnumBounded = encodeInt . fromEnum
```suggestion
encodeEnum :: Enum a => a -> Encoding
encodeEnum = encodeInt . fromEnum
```

2023-01-04 14:51 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoteDecision) && n <= fromEnum (maxBound :: VoteDecision)
@aniketd By `safeToEnum` Joosep meant `decodeEnumBounded`

2023-01-04 15:55 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      if n >= fromEnum (minBound :: VoteDecision) && n <= fromEnum (maxBound :: VoteDecision)
Oh! Got you! :+1:

2023-01-04 18:06 UTC, lehins approved these changes
Looks great!

2023-01-04 21:06 UTC, merged