Added `VState`, Renamed `DPState` to `CertState`
IntersectMBO/cardano-ledger pull request #3369
Opened 2023-04-05 12:08 UTC by Soupstraw

# Description

This PR renames `DPState` to `CertState` and adds the VState field to it.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-04-05 18:10 UTC, JaredCorduan approved these changes
Looks great to me!

I suspect that the "crypto parametrization to era parametrization" change will cause a bit of downstream work, so that we should not merge this until @lehins is ready for the final ledger release.

2023-04-13 21:03 UTC, lehins requested changes
This is great work. Couple of general comments:

* We need to be more diligent with versions and bounds. It is much easier to fix the bounds in the same PR that introduces breaking changes, rather than afterwards
* Reusing DELEG rule from shelley can be better. We can discuss this one later

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +          (KeyHash 'Voting (EraCrypto era))
Not suggest we do this in this PR. We need to think about either creating newtype wrappers around these KeyHashes, or creating another KeyRole. We need to disambiguate these two somehow, otherwise it is way too easy to mess them up.

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +  , certVState :: !(VState era)
Considering that you are already changing this type can you swap the order of `certPState` and `certDState` as well? It will be less confusing because that is the order they are being serialized. Also it is better for sharing to put `VState` first (or at least before `DState`), this is because the credentials of DReps then can be shared inside the `DState`. I'll submit a separate PR that fixes the sharing, cause I don't think I'll be able to figure it out directly in github without the help of a type checker.
```suggestion
  { certVState :: !(VState era)
  , certPState :: !(PState era)
  , certDState :: !(DState era)
```

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +      <> encCBOR certVState
As I mentioned in the previous comment, this will be better for sharing
```suggestion
      <> encCBOR certVState
      <> encCBOR certPState
      <> encCBOR certDState
```

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +    certVState <- lift decCBOR
I'll fix it properly later, but let's at least fix the ordering.
```suggestion
    certVState <- lift decCBOR -- TODO: add sharing of DRep credentials
    certPState <- decSharePlusLensCBOR _2
    certDState <- decSharePlusCBOR
```

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Core/Arbitrary.hs
> +  shrink = genericShrink
Generic shrink doesn't work right on Maps. We should probably remove it fro `PState` and `DState` as well
```suggestion
```

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Generic/Same.hs
> +    extendLabel "DState " (same proof d1 d2) ++ extendLabel "PState " (same proof p1 p2) ++ extendLabel "VState " (same proof v1 v2)
Line is getting a little too long
```suggestion
    extendLabel "DState " (same proof d1 d2) ++ 
    extendLabel "PState " (same proof p1 p2) ++ 
    extendLabel "VState " (same proof v1 v2)
```

2023-04-13 21:03 UTC, lehins commented on eras/allegra/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
This is not a relevant change for Allegra
```suggestion
```

2023-04-13 21:03 UTC, lehins commented on eras/allegra/impl/CHANGELOG.md
> +## 1.2.0.0
As far as `cardano-ledger-allegra` package is concerned this is not a breaking change.

Also need to be updated in cabal file
```suggestion
## 1.1.1.0
```

2023-04-13 21:03 UTC, lehins commented on eras/alonzo/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Same here and cabal file
```suggestion
## 1.1.1.0

* Replace `DPState c` with `CertState era`
```

2023-04-13 21:03 UTC, lehins commented on eras/babbage/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Same here and cabal file
```suggestion
## 1.1.1.0

```

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Not a change relevant for this package
```suggestion
* Replace `DPState c` with `CertState era`
```

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Delegs.hs
> +  | CertFailure (PredicateFailure (EraRule "CERT" era)) -- Subtransition Failures
It would be good to turn those into haddock, rather tyhan comments
```suggestion
  = DelegateeNotRegisteredDELEG !(KeyHash 'StakePool (EraCrypto era))
   -- ^ Target pool which is not registered
  | WithdrawalsNotInRewardsDELEGS !(Map (RewardAcnt (EraCrypto era)) Coin)
   -- ^ Withdrawals that are missing or do not withdrawal the entire amount
  | CertFailure (PredicateFailure (EraRule "CERT" era))
   -- ^ Sub-transition Failures
```

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Delegs.hs
> +import Cardano.Ledger.Shelley.API (CertState, Coin, DCert, DState, DelegsEnv, DelplEnv, KeyHash, KeyRole (..), PState, RewardAcnt)
Maybe turn into a multiline?

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Delegs.hs
> +      ConwayDelegsPredFailure era
On the other hand this isn't too long, and switching it a single line will make it more consistent with the rest of type family instances above and below
```suggestion
  type PredicateFailure (ConwayDELEGS era) = ConwayDelegsPredFailure era
```

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/CHANGELOG.md
> +## 1.2.0.0
This is a correct bump. However, all versions also need to be bumped in the cabal file, not only in the changelog.

Also, because this change is now required by all of the packages that have been modified in this PR, they all need to get a lower bound update: `cardano-ledger-core ^>= 1.2`

2023-04-13 21:03 UTC, lehins commented on eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Translation.hs
> +        }
I think this is one one of those places where RecordWildCards really shine:
I'd suggest this change on the introduced translations for `PState` and `DState` in other packages as well.

However, there is nothing wrong with current implementation, so it is up to you if you wanna change it or not.
```suggestion
  translateEra _ DState {..} = pure DState {..}
```

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ledger.hs
> +  let CertState dstate _pstate _vstate = dpstate
This will also need a rename of the binding as well
```suggestion
  let dstate = certDState certState
```

2023-04-13 21:03 UTC, lehins commented on eras/mary/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Ditto
```suggestion
## 1.1.1.0

```

2023-04-13 21:03 UTC, lehins commented on eras/shelley/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
In `cardano-ledegr-shelley` this change is somewhat relevant, but only because it affected types of arguments for some of the functions, which is a user facing feature.

2023-04-13 21:03 UTC, lehins commented on eras/shelley/impl/CHANGELOG.md
> +## 1.2.0.0
This is indeed a breaking change, which means all of the downstream packages (like `cardano-ledger-shelley-test`) that have been affected by this change now need a lower bound update. Naturally this version also need to be updated in the cabal file

2023-04-13 21:03 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs
> +  , Signal someCERT ~ DCert (EraCrypto era)
This whole approach of reusing `delegsTransition` in CONWAY isn't gonna work, at least not the way you are doing it. 

Note that the certificate `DCert` will be different in Conway, so that is already a problem. 

I suggest reverting changes to DELEGS in this PR and handling it as a separate PR in a different manner.

There is a better way of solving this problem. The classic way: extracting parts of the `delegsTransition` into separate functions and reusing them directly in a newly defined CERT rule. This whole complication with `ShelleyDelegsFail`  is definitely an unnecessary complication.

2023-04-13 21:03 UTC, lehins commented on eras/shelley/impl/CHANGELOG.md
> +* Add `ShelleyDelegsFail` typeclass
Not to forget removing it from the changelog too
```suggestion
```

2023-04-13 21:03 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Epoch.hs
> +  let adjustedDPstate = CertState dstate' pstate'' vstate
```suggestion
  let adjustedCertState = CertState dstate' pstate'' vstate
```

2023-04-13 21:03 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +data VState era = VState
So, we plan to add DRep Deposits into this type later, right?

2023-04-13 21:03 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/PoolReap.hs
> +            obligationCertState (CertState (prDState st) (prPState st) def) == utxosDeposited (prUTxOSt st)
I suspect this `def`  will be a problem when we add DRep deposits. I think we might have to add the full `CertState` to the `ShelleyPoolreapState`. 

We don't have to solve it now in this PR though. However, might be worth noting as a TODO.

2023-04-13 21:03 UTC, lehins commented on eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Generator/Update.hs
> +          (GenDelegs genDelegs) = (dsGenDelegs . certDState) delegPoolSt
I know you didn't write this, but this is bugging me anyways :slightly_smiling_face: 
```suggestion
          GenDelegs genDelegs = dsGenDelegs (certDState delegPoolSt)
```

2023-04-13 21:03 UTC, lehins commented on eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Rules/Deposits.hs
> +  let LedgerState {lsCertState = CertState dstate _ _} = (esLState . nesEs . chainNes) chainSt
This will help with fields reordering
```suggestion
  let LedgerState {lsCertState = CertState {certDState = dstate}} = (esLState . nesEs . chainNes) chainSt
```

2023-04-13 21:03 UTC, lehins commented on eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Rules/IncrementalStake.hs
> +          ptrs' = ptrsMap . certDState $ dp'
I just don't get it why people write it that way
```suggestion
          ptrs = ptrsMap $ certDState dp
          ptrs' = ptrsMap $ certDState dp'
```

2023-04-13 21:03 UTC, lehins commented on eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Rules/TestChain.hs
>         in poolSt0_
This is way more compact and forward compatbile
```suggestion
       credPState (lsCredState ledgerSt0)
```

2023-04-13 21:03 UTC, lehins commented on eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Rules/TestChain.hs
>         in delegSt0_
Same here
```suggestion
      credDState (lsCredState ledgerSt0)
```

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Delegs.hs
> +  transitionRules = [delegsTransition @_ @(EraRule "CERT" era) @(ConwayDELEGS era) @(ShelleyDelplPredFailure era)]
We gonna have to redefine this rule from scratch. Reusing it like that will not work
```suggestion
  transitionRules = []
```
Let's do it in a separate PR though.

2023-04-13 21:03 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Delegs.hs
> +  certFailure = CertFailure
Not applicable
```suggestion
```

2023-04-14 09:50 UTC, Soupstraw commented on eras/allegra/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
My thinking was that these changes cause the constraints of some of the functions in this package to change.

2023-04-14 10:15 UTC, Soupstraw commented on eras/shelley/test-suite/src/Test/Cardano/Ledger/Shelley/Rules/IncrementalStake.hs
> +          ptrs' = ptrsMap . certDState $ dp'
I usually don't write it like this either, but this one somehow slipped in

2023-04-14 11:21 UTC, Soupstraw commented on eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Translation.hs
> +        }
That's pretty clever. I updated the other `translateEra`s as well.

2023-04-14 11:33 UTC, Soupstraw commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +data VState era = VState
Right now the plan is to keep track of all the deposits in UTxOState.

2023-04-14 12:56 UTC, lehins commented on eras/allegra/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Which functions? I didn't see any changes to constraints

2023-04-14 13:01 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +data VState era = VState
That is strange. Deposits for PoolStake operators and Delegators is kept in CertState. What is the reasoning for DReps' deposits to be in a different place?

2023-04-14 13:02 UTC, Soupstraw commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +          (KeyHash 'Voting (EraCrypto era))
That sounds like an easy fix, I'll do it in this PR.

2023-04-14 13:11 UTC, Soupstraw commented on eras/allegra/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Oh, ok that's right

2023-04-14 13:13 UTC, Soupstraw commented on eras/conway/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
But this one does have some changes in constraints related to the `CertState` renaming

2023-04-14 13:17 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Parametrize `DState` and `PState` by era
Fair enough. Then only one of those entries is needed.

2023-04-18 15:26 UTC, lehins approved these changes
Awesome work. Thank you!

2023-04-18 15:26 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Replace `DELPL` rule with `CERT`
Technically not in this PR, but feel free to leave it in since you are doing this in #3384 anyways

2023-04-18 15:26 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Delegs.hs
> +  certFailure = DelplFailure
Remnants of a previous attempt
```suggestion
```

2023-04-18 15:26 UTC, lehins commented on libs/cardano-ledger-core/src/Cardano/Ledger/CertState.hs
> +data VState era = VState
We can deal with this later no need to worry about deposits in this PR

2023-04-19 10:29 UTC, aniketd approved these changes
LGTM :raised_hands:

2023-04-19 13:43 UTC, merged