Bump plutus-core to 1.5.0.0
IntersectMBO/cardano-ledger pull request #3382
Opened 2023-04-17 16:13 UTC by zliu41

2023-04-17 16:13 UTC, zliu41 commented on eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs
> -    safeFromInteger :: Integral a => a -> Maybe Natural
SatInt no longer has Integral instance

2023-04-17 16:23 UTC, zliu41 commented
To be done in https://github.com/input-output-hk/cardano-ledger/pull/3365 instead.

2023-04-18 09:59 UTC, michaelpj commented
I think we should do this independently anyway. The version bump should be independent from actually starting to use the new features!

2023-04-18 11:45 UTC, lehins requested changes
Couple of required steps are missing, otherwise looks good.

2023-04-18 11:45 UTC, lehins commented on cabal.project
> +  , cardano-haskell-packages 2023-04-17T14:00:00Z
You need to run `niv update cardano-haskell-packages` to update sources too.

See [CONTRIBUTING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/CONTRIBUTING.md#updating-dependencies)

2023-04-18 11:45 UTC, lehins commented on eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts/Data.hs
> -deriving instance NoThunks PV1.Data
Removal of an orphan instance requires a major version pump in a package, so it should be set to: `cardano-ledger-alonzo-1.2.0.0`

2023-04-18 18:36 UTC, lehins approved these changes
:+1: Thank you

2023-04-18 19:55 UTC, merged