Remove Sums Class
IntersectMBO/cardano-ledger pull request #3475
Opened 2023-06-07 14:11 UTC by aniketd

# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-06-07 14:13 UTC, aniketd commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Spec.hs
> +--     Nothing -> ElemNever ["The ElemSpec's are inconsistent.", "  " ++ show a, "  " ++ show b]
@TimSheard There seems to be know way to merge the specs once we use lenses, am I correct?

2023-06-12 16:26 UTC, TimSheard requested changes

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
> +
increaseBy1  decreaseBy1

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
> +
zero - x

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
>        (minus ("Ex steps" : msgs) b d)
minus on ExUnits memory

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
> +--       ms = msgs ++ ["genAdds DeltaCoin"]
No need for this.

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
> +  LTH -> SzMost $ toI $ decrease [unlines ["ordCondToSize failed for", label, show n]] n
decrease n = pair (i-1) (j-1)  where (i,j) = unpair n


EQL -> SzExact $ toI n
LTH -> SzMost $ decrease [unlines ["ordCondToSize failed for", label, show n]] (toI n)
 GTH -> SzLeast $ increase (toI n)

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
> +vLeftSize x cond n = ordCondToSize (x, cond, n)
vLeft --> varOnLeft

vRightSize  --> varOnRightSize

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Spec.hs
> +--     Nothing -> ElemNever ["The ElemSpec's are inconsistent.", "  " ++ show a, "  " ++ show b]
yes

2023-06-12 16:26 UTC, TimSheard commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Solver.hs
>   )
At all these call sites. One MUST get rid of the toI ,

2023-06-15 12:11 UTC, aniketd commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
> +
Removed `negateAdds` altogether, following our conversation :+1:

2023-06-15 14:27 UTC, aniketd commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Constrained/Classes.hs
>        (minus ("Ex steps" : msgs) b d)
I don't exactly remember what this comment was for, during our discussion @TimSheard. Can we discuss on Slack?

2023-07-21 10:11 UTC, merged