WIP - Separate Procedures
IntersectMBO/cardano-ledger pull request #3521
Opened 2023-07-04 11:41 UTC by Soupstraw

# Description

resolve #3513 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-07-05 13:57 UTC, aniketd approved these changes
Awesome! :raised_hands:

2023-07-05 14:00 UTC, lehins requested changes
This is perfect. Due to a new release a few more things are needed: 
* Version bump
* Update to deps and version bump in `cardano-ledger-conway-test`

2023-07-05 14:00 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs
> +import Cardano.Ledger.Binary (DecCBOR (..), EncCBOR (..), decodeEnumBounded, decodeNullStrictMaybe, encodeEnum, encodeListLen, encodeNullStrictMaybe, encodeWord8, invalidKey)
Could you please switch this to a multi-line

2023-07-05 14:00 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Removal of `GovernanceProcedure` in favor of `GovernanceProcedures`
Let's start a new section and a bump to the cabal version: `1.6.0.0`

`1.5.0.0` just has been released an hour ago.

2023-07-05 14:25 UTC, lehins commented on libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal
Sorry, a patch version for this package need to be updated too.

2023-07-05 14:50 UTC, Soupstraw commented on libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal
The last release seems to be `1.2.0.1` according to `git tag -l`

2023-07-05 14:51 UTC, Soupstraw commented on libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal
ok, I see that they released 1.2.1.1

2023-07-06 13:16 UTC, lehins approved these changes
Perfect!

2023-07-06 13:16 UTC, merged