Make CC Cold Key a Credential
IntersectMBO/cardano-ledger pull request #3581
Opened 2023-07-26 16:32 UTC by aniketd

# Description

Resolves #3564 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-07-26 16:40 UTC, lehins requested changes
Looks good. Couple of suggestions and you are still missing changes to the CDDL spec

2023-07-26 16:40 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs
> +      _ -> Nothing
Reduce the clutter and reuse specialized `credScriptHash` function
```suggestion
  ConwayTxCertCommittee committeeCert -> 
    case committeeCert of
      ConwayAuthCommitteeHotKey coldCred _hotCred -> credScriptHash coldCred
      ConwayResignCommitteeColdKey coldCred -> credScriptHash coldCred
  _ -> Nothing
```

2023-07-26 16:40 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs
> +      _ -> Nothing
Same here:
```suggestion
  ConwayTxCertCommittee committeeCert -> 
    case committeeCert of
      ConwayAuthCommitteeHotKey coldCred _hotCred -> credKeyHashWitness coldCred
      ConwayResignCommitteeColdKey coldCred -> credKeyHashWitness coldCred
      _ -> Nothing
```

2023-07-27 11:18 UTC, lehins approved these changes
:+1:

2023-07-27 13:53 UTC, aniketd commented on eras/conway/impl/CHANGELOG.md
> +  * committee hot keys to be script-hashes #3552
@lehins noted! :memo: :raised_hands: Thank you!

2023-07-27 15:13 UTC, merged