Update `ProposalProcedure` return address to be a `Credential`
IntersectMBO/cardano-ledger pull request #3597
Opened 2023-08-02 09:54 UTC by teodanciu

# Description

Closes https://github.com/input-output-hk/cardano-ledger/issues/3594

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-08-02 09:55 UTC, teodanciu commented
I assume `scriptsNeeded` doesn't have to be updated for this, please correct me if I'm wrong

2023-08-03 11:47 UTC, lehins requested changes
During a meeting yesterday we figured out a discrepancy. This has to be a RewardAcnt, not just a Credential

2023-08-03 11:47 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +  , gasReturnAddr :: !(Credential 'Staking (EraCrypto era))
Turns out it actually has to be a reward account, not just a `Credential`
```suggestion
  , gasReturnAddr :: !(RewardAcnt (EraCrypto era))
```

2023-08-04 12:30 UTC, teodanciu commented
I updated it to be a RewardAcnt, however, I haven't used the `Network` anywhere. 
I assume it will be needed (otherwise why have it), but not sure if at this point. Maybe in the way we insert in UMap in Epoch rule?

2023-08-04 12:40 UTC, lehins commented
We'll only need to validate that the NetworkId matches the network we are running. That's all.

See this ticket I created: https://github.com/input-output-hk/cardano-ledger/issues/3603

2023-08-04 12:41 UTC, lehins approved these changes
Great. Thank you!

2023-08-04 12:41 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Update `ProposalProcedure` return address to be a `Credential`
```suggestion
* Update `ProposalProcedure` return address to be a `RewardAcnt`
```

2023-08-04 14:20 UTC, merged