Aniketd/rename governance to gov
IntersectMBO/cardano-ledger pull request #3607
Opened 2023-08-07 09:18 UTC by aniketd

# Description

Resolves #3544 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-08-07 16:09 UTC, lehins requested changes
A couple of things need a change, but otherwise looks great.

2023-08-07 16:09 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +  * `ConwayGovState` to `GovActionMap`
It is bad practice to name types with data structure that it uses. The data strucutre can change in the future to something else (eg. assoc list, or addition of a new field), and then the name of the type would have to be changed as well. So, it is better to name types what they actually represent, rather than how they are implemented. In this case, it is the state for gov actions, so plural would work just fine, I think:
```suggestion
  * `ConwayGovState` to `GovActionsState`
```

2023-08-07 16:09 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +  * module `Cardano.Ledger.Conway.Rules.Governance` to `Cardano.Ledger.Conway.Rules.Gov`
There was never a module with such name: `Cardano.Ledger.Conway.Rules.Governance`
```suggestion
```

2023-08-07 16:09 UTC, lehins commented on eras/conway/test-suite/cddl-files/conway.cddl
> +  , ? 30: coin                   ; gov action deposit
These are comments. I think to use full names in textual comments
```suggestion
  , ? 29: uint                   ; governance action expiration
  , ? 30: coin                   ; governance action deposit
```

2023-08-07 16:09 UTC, lehins commented on eras/conway/test-suite/cddl-files/conway.cddl
> +  , unit_interval ; PP gov group
Same here
```suggestion
  , unit_interval ; PP governance group
```

2023-08-07 16:09 UTC, lehins commented on libs/cardano-ledger-api/src/Cardano/Ledger/Api.hs
> +  -- | Gov
This is haddock, we wanna use full names in documentation.
```suggestion
  -- | Governance
```

2023-08-07 16:09 UTC, lehins commented on libs/cardano-ledger-api/src/Cardano/Ledger/Api/Gov.hs
> +  -- ** Gov Action
Same here
```suggestion
  -- ** Governance Action
```

2023-08-07 16:09 UTC, lehins commented on eras/shelley/impl/CHANGELOG.md
> +  * `GovernanceState` to `GovState`
```suggestion
  * `GovernanceState` to `GovState`
  * `witsVKeyNeededNoGovernance` to `witsVKeyNeededNoGov`
  * `witsVKeyNeededGovernance` to `witsVKeyNeededGov`
  * `utxosGovernance` to `utxosGovState`
```

2023-08-07 16:09 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/API/ByronTranslation.hs
> +              , utxosGov = emptyGovState
Could you also rename this to reflect that it a `State`
```suggestion
              , utxosGovState = emptyGovState
```

2023-08-07 16:09 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState.hs
> +  utxosGovL,
Same suggestion for the lens
```suggestion
  utxosGovStateL,
```

2023-08-08 12:07 UTC, aniketd commented on eras/conway/impl/CHANGELOG.md
> +  * `ConwayGovState` to `GovActionMap`
Got it. Thanks Alexey! :raised_hands:

2023-08-08 18:49 UTC, lehins approved these changes
Beautiful! Thank you!

2023-08-08 20:19 UTC, merged