Add rule-transition diagrams in dot syntax
IntersectMBO/cardano-ledger pull request #3629
Opened 2023-08-09 14:47 UTC by aniketd

Motivation: Since,
1. there have been multiple occasions where we have liked to refer to the rule-transition diagram in the Shelley specification during our technical discussions, and
2. now for Conway such a diagram does not exist yet, and
3. we do not have replaced a prose-in-tex based format for specifications in Agda,

I thought it would be a good idea to keep these diagrams handy, "as graphviz dot code" (and its output) in version control for everyone's benefit.

**I may be completely wrong and we can close this PR if this is not very helpful.**

NOTE: It is still a draft, since I'm not entirely certain about the accuracy of the Conway rule transitions yet, and would like @WhatisRT or @Soupstraw 's review, especially on the rules that have been removed, etc.

NOTE: A good way to review the rendered SVG files is to click on the `raw` button to view it directly on the browser, instead of within the GitHub UI.

2023-08-09 15:46 UTC, aniketd commented
Good additions:
1. Environment
2. Signal

2023-08-09 15:51 UTC, aniketd commented
TODO: Consider adding the 4 triggers in concensus that cause the rule transitions.

2023-08-21 11:49 UTC, aniketd commented
Haven't been able to come to this one yet. The TODOs remain:
1. Convert all circles to boxes (trivial)
2. Add (Env, State, Signal) triple to all nodes in a readable manner (should be easy)
3. Add the _four triggers from consensus_ to consider the transition diagrams actually complete.

2023-08-24 12:18 UTC, aniketd commented
Updating the transition diagram for Shelley with boxes and more details is left for later, when more bandwidth is available.

2023-08-29 15:14 UTC, Soupstraw requested changes

2023-08-29 15:14 UTC, Soupstraw commented on docs/graphviz-diagrams/conway_transitions.gv
> +    NEWPP    [shape=box, label="NEWPP (shelley)    \nenv:NewppEnv,state:ShelleyNewppState,signal:Maybe(PParams)."];
We don't have those in Conway

2023-08-29 15:14 UTC, Soupstraw commented on docs/graphviz-diagrams/conway_transitions.gv
> +    NEWPP    [shape=box, label="NEWPP (shelley)    \nenv:NewppEnv,state:ShelleyNewppState,signal:Maybe(PParams)."];
```suggestion
```

2023-08-29 15:15 UTC, Soupstraw commented on docs/graphviz-diagrams/conway_transitions.gv
> +    UPEC -> NEWPP;
```suggestion
```

2023-09-06 08:16 UTC, lehins approved these changes
LGTM.
Thank you for doing this

2023-09-07 09:49 UTC, lehins commented on docs/graphviz-diagrams/conway_transitions.gv
Don't merge until #3697 is merged

2023-09-07 09:50 UTC, aniketd commented on docs/graphviz-diagrams/conway_transitions.gv
Noted! :memo:

2023-09-07 19:37 UTC, lehins commented
@Soupstraw Need your unblock on this PR

2023-09-11 16:02 UTC, Soupstraw approved these changes

2023-09-11 16:02 UTC, merged