Preserve the order of ProposalProcedures
IntersectMBO/cardano-ledger pull request #3690
Opened 2023-08-30 14:39 UTC by Soupstraw

# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-08-31 16:37 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/TxBody.hs
> +class BabbageEraTxBody era => ConwayEraTxBody era where
Looks like you need to add `UndecidableSuperClasses`

2023-09-01 17:12 UTC, lehins requested changes
I haven't fully finished reviewing it. 
I'll do a second pass on Monday

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +    psSeq :: !(StrictSeq (GovActionId (EraCrypto era)))
It is bad practice to name record fields with data structures that they use, cause we might change it in the future. It should have some sort of semantic meaning. Something like:
```suggestion
  { psGovActionStates :: !(Map (GovActionId (EraCrypto era)) (GovActionState era))
  , -- | Newer actions are near the end
    psProposalOrder :: !(StrictSeq (GovActionId (EraCrypto era)))
```

Also it is good to turn comments like this into haddock

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +        Nothing -> error "ProposalsSnapshot invariant is not maintained"
Mark it as impossible and in case if it does happen, showing the offender is a good idea for debugging:
```suggestion
        Nothing -> 
          error $ "Impossible: ProposalsSnapshot invariant is not maintained: "
                <> Text.unpack (govActionIdToText gaId)
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +        Just v -> v :<| helper xs
It is common to name such function either `loop` or `go`. Also, not necessary, but a slight improvement to naming of bindings, so it is clear what we are looping over
```suggestion
    go (gaId :<| gaIds) =
      case Map.lookup x psMap of
        Just v -> gaId :<| go gaIds
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +  Map.elems psMap
It is ok to return a Map. The only thing we use it for is to fold over, which can be done over a Map. Also, we never know it might come in handy.
```suggestion
snapshotGovActionStates ::
  ProposalsSnapshot era ->
  Map (GovActionId GovActionState era]
snapshotGovActionStates = psMap
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +    }
Whenever you can use NamedFIeldPuns, instead of RecordWildCards.

Also this function isn't quite correct, because it allows duplicate govActionIds in the sequence. This is not something that can happen in our system, if we implement it correctly, but nonetheless we should account for it somehow
```suggestion
snapshotInsertGovAction gas@GovActionState {gasId} ps@ProposalsSnapshot {..}
  | Map.member gasId psMap = 
    ps { psMap = Map.insert gasId gas psMap }
  | otherwise = 
    ProposalsSnapshot
      { psMap = Map.insert gasId gas psMap
      , psSeq = psSeq :|> gasId
      }
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +    }
This approach in the end results in (O(n*m)) operations, which is not good since it is quadratic.

It is better to convert it to plural removal.

```suggestion
snapshotRemoveIds ::
  Set (GovActionId (EraCrypto era)) ->
  ProposalsSnapshot era ->
  ProposalsSnapshot era
snapshotRemoveIds gIds (ProposalsSnapshot {..}) =
  ProposalsSnapshot
    { psMap = psMap `Map.withoutKeys` gIds
    , psSeq = foldl' (\s x -> if x `Set.member` gIds then s else x :<| s) mempty psSeq
    }
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +unsafeFromGovActionStateSeq Empty = def
It was `snapshotInsertGovAction` that was unsafe. Because of my suggestion in  `snapshotInsertGovAction` that fixes it, this can be changed to:
```suggestion
fromGovActionStateSeq ::
  StrictSeq (GovActionState era) ->
  ProposalsSnapshot era
fromGovActionStateSeq (x :<| xs) =
  snapshotInsertGovAction
    x
    (unsafeFromGovActionStateSeq xs)
fromGovActionStateSeq Empty = def
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +  sort (Map.keys psMap) == sort (toList psSeq)
`keys` already produces a sorted list.
```suggestion
  Map.keys psMap == sort (toList psSeq)
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +    && all (\(k, GovActionState {..}) -> k == gasId) (Map.toList psMap)
Please try not to abuse REcordWildCards so much
```suggestion
    && all (\(k, GovActionState {gasId}) -> k == gasId) (Map.toList psMap)
```

2023-09-01 17:12 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +isConsistent_ (ProposalsSnapshot {..}) =
Same here
```suggestion
isConsistent_ (ProposalsSnapshot {psMap, psSeq}) =
```

2023-09-04 12:07 UTC, lehins approved these changes
This looks good. 

General feedback:

* Nice job on creating a safe interface for GovSnapshots :muscle: 
* It would have been much easier to review the PR if all the non-semantic changes like code moving (`ConwayEraTxBody`, `Params stuff`, etc) was done in a separate commit. I know it requires work and sometimes such change hard to predict and separate from the reset of the work. I am just saying that whenever possible we should try and do that. No need to split this PR into multiple commits.

2023-09-04 12:07 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Snapshots.hs
> +-- Snapshot will be malformed!
It will no longer be malformed, duplicates will just get dropped.
```suggestion
-- | Converts a sequence of `GovActionState`s to a `ProposalsSnapshot`.
-- 
-- /Warning/ - This function expects `GovActionState`'s to have unique 
-- `GovActionId`s, because duplicate Ids will result in `GovActionStates` 
-- to be dropped.
```

2023-09-04 12:07 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +        (foldl' (\s x -> Set.insert (gasId x) s) mempty rsRemoved)
Potential easy optimization:

I think it would make sense to switch `rsRemoved` to have the type:
```haskell
rsRemoved :: !(Set (GovActionId (EraCrypto era)))
```
Instead of doing this conversion here. We don't really care in which order GovActions get removed.

2023-09-04 12:07 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +  let unknownGovActionIds = foldl' (flip Set.delete) gaIds (snapshotIds $ curGovSnapshots gas)
This is less efficient, because you iterate over the whole sequence of current governance actions, instead of a small number of proposed governance actions. This is optimal:
```suggestion
  let curGovActionIds = snapshotGovActionStates $ curGovSnapshots gas
      unknownGovActionIds = Set.filter (`Map.notMember` curGovActionIds) gaIds
```

Difference in complexity is `n * log m` vs `m * log n`, where `n` (number of current gov actions) is known to be always much bigger than `m` (number of proposed gov actions)

2023-09-04 12:07 UTC, lehins commented on libs/cardano-ledger-pretty/cardano-ledger-pretty.cabal
> +version:            1.3.2.0
`1.3.1.0` hasn't been released yet. You can learn this info from the CHANGELOG (latest version in it matches the current one), from git tag or from CHaP
```suggestion
version:            1.3.1.0
```

2023-09-04 12:07 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Move `ConwayEraPParams` to `Cardano.Ledger.Conway.PParams` together with
Did you try to add something at the end? Together with something?
```suggestion
* Move `ConwayEraPParams` to `Cardano.Ledger.Conway.PParams`
```

2023-09-04 12:07 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Core.hs
> -  ppuDRepActivityL,
Can you try re-export all of these? Since dependency direction got flipped, we should be able to import all these guys into this module.
This will reduce breakage downstream and continue providing ability for us to export all core types from `.Core` module. At least until we are ready to change it up a bit.

2023-09-04 12:07 UTC, lehins commented on eras/conway/test-suite/test/Test/Cardano/Ledger/Conway/GovSnapshot.hs
Is there any chance you could move these tests as hspec tests into `cardano-ledger-conway:tests` as well? Just as in #3698

This will have a new module name `Test.cardano.Ledger.GovSnapshotSpec`

2023-09-04 13:16 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Core.hs
> -  ppuDRepActivityL,
the PParams and UTxO module still depend on Core

2023-09-04 13:31 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Core.hs
> -  ppuDRepActivityL,
:cry: That's alright. Not the end of the world, especially since we'll be getting rid of those Core modules in the future anyways.

2023-09-05 12:41 UTC, Soupstraw commented on eras/conway/test-suite/test/Test/Cardano/Ledger/Conway/GovSnapshot.hs
I'll not do it this time since we might actually have to remove the tests anyways after the optimization is done.

2023-09-05 16:04 UTC, merged