Delay all enactments by one extra epoch
IntersectMBO/cardano-ledger pull request #3719
Opened 2023-09-08 10:30 UTC by Soupstraw

# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-09-08 18:11 UTC, teodanciu commented
Thanks for writing the example! 

In the implementation, where is this part? 

```If P has enough votes:
  - Apply P onto `cgFutureEnactState`
Remove P from the snapshots
```

2023-09-11 10:08 UTC, lehins requested changes
I am very suspicious of the EnactState argument to the RATIFY rule. We should do some more analysis and more tests in order to ensure we got it right.

2023-09-11 10:08 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      , "futureEnact" .= cgEnactState
```suggestion
      , "futureEnactState" .= cgFutureEnactState
```

2023-09-11 10:08 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs
> +      , "curEnact" .= cgEnactState
Nice catch on `ratify`. Let's give it a more complete name
```suggestion
      , "curEnactState" .= cgEnactState
```

2023-09-11 10:08 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +            , rsEnactState = futureEnactState
Are you sure this is suppose to be `futureEncastState`? I could of course be wrong, but in my understanding it should be `govSt ^. cgEnactStateL`.

2023-09-11 10:08 UTC, lehins commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Examples/ConwayFeatures.hs
> +  epochState4 <- expectRight "Error running runEPOCH: " $ runEPOCH (EPOCH pf) epochState3' (EpochNo 5) poolDistr
This looks slightly wrong, why do we run EPOCH rule on the same epoch number, but different state? Also we should stick to one convention of either ticks or numbers, without mixing them in the same function:
```suggestion
  epochState4 <- expectRight "Error running runEPOCH: " $ runEPOCH (EPOCH pf) epochState3 (EpochNo 5) poolDistr
  epochState5 <- expectRight "Error running runEPOCH: " $ runEPOCH (EPOCH pf) epochState4 (EpochNo 6) poolDistr
```

2023-09-11 10:08 UTC, lehins commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Examples/ConwayFeatures.hs
> +  epochState1' <-
Same here could you avoid mixing ticks with numbers. It is hard to follow the dependency order

2023-09-11 10:08 UTC, lehins commented on libs/cardano-ledger-test/src/Test/Cardano/Ledger/Examples/ConwayFeatures.hs
> +      runEPOCH (EPOCH pf) epochState1' (EpochNo 3) poolDistr
Again same EpochNo as in the previous call to runEPOCH

2023-09-11 10:55 UTC, WhatisRT reviewed
I'm not sure I can provide a meaningful review, as I've got no idea how the delay for the incremental computation works. To me the code that didn't get changed looks completely wrong already, since all the inputs to `RATIFY` need to be snapshotted (if they aren't known statically), but it looks to me like the ingredients of `ratEnv` are just computed (transitively) from `es`.

2023-09-11 11:30 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +            , rsEnactState = futureEnactState
I think it should be `futureEnactState`, because that's where we stored the enactments last epoch.

2023-09-11 13:11 UTC, lehins commented
> since all the inputs to RATIFY need to be snapshotted

@WhatisRT They are snapshotted. Stake distribution for Pools and DReps is from the previous epoch. We just need to make sure that the starting EnactState for the RATIFY rules also comes from the previous epoch

2023-09-11 13:24 UTC, Soupstraw commented
> Thanks for writing the example!
> 
> In the implementation, where is this part?
> 
> ```
>   - Apply P onto `cgFutureEnactState`
> Remove P from the snapshots
> ```

This is when we run `RATIFY` using `futureEnactState`

2023-09-13 16:15 UTC, teodanciu commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +    futureEnactState = govSt ^. cgFutureEnactStateL
As we said in the meeting, `enactState` would be a less confusing name than `futureEnactState`

2023-10-05 22:57 UTC, lehins commented
This can be closed, as we decided not use this approach and instead we'll run RATIFY rule two stability windows before the end of the epoch (implemented in #3759), thus allowing us to postpone enactment only for one epoch, rather than two.

2023-10-05 22:57 UTC, closed without merging