Made HardFork action drop all other actions
IntersectMBO/cardano-ledger pull request #3720
Opened 2023-09-08 13:19 UTC by Soupstraw

# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-09-13 10:28 UTC, lehins commented on eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Arbitrary.hs
> +    ]
Derive Enum and Bounded and you can use this implementation:
```suggestion
  arbitrary = arbitraryBoundedEnum
  shrink = shrinkBoundedEnum
```

2023-09-13 12:23 UTC, lehins requested changes
Except one potential mistake, this looks good.

2023-09-13 12:23 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs
> +actionFutureStrategy InfoAction {} = Delay
I think you mixed them up
```suggestion
actionFutureStrategy NoConfidence {} = Delay
actionFutureStrategy NewCommittee {} = Delay
actionFutureStrategy NewConstitution {} = Delay
actionFutureStrategy TreasuryWithdrawals {} = Continue
actionFutureStrategy ParameterChange {} = Continue
actionFutureStrategy InfoAction {} = Continue
```

2023-09-13 12:31 UTC, Soupstraw commented
I'm thinking this wouldn't probably work the way I did it. We also somehow have to prevent adding new GAs after HF is ratified.

2023-09-13 12:35 UTC, lehins commented
> I'm thinking this wouldn't probably work the way I did it. We also somehow have to prevent adding new GAs after HF is ratified, probably by storing the RatifyStrategy for future epochs.

@Soupstraw It would work, you just haven't implemented it all the way

We need another flag in the enact state that would prevent new proposals whenever Ratify ended with a Drop strategy

2023-09-14 10:56 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Ratify.hs
> +actionFutureStrategy InfoAction {} = Delay
nice catch!

2023-09-14 19:31 UTC, lehins commented
I think it will be better to clear out all of the proposals during translation, which will be implemented in the next era after Conway.

It would make a little more sense if we were leaning towards delaying for two epochs, but since now this is changing, dropping proposals at the same time we do a hardfork makes the rule a bit more complicated than it should be.

2023-09-14 19:31 UTC, closed without merging