Apply enacted treasury withdrawals
IntersectMBO/cardano-ledger pull request #3748
Opened 2023-09-21 16:05 UTC by aniketd

# Description

Closes #3736 

In GovAction,
TreasuryWithdrawals !(Map (RewardAcnt crypto) Coin) has been changed to
TreasuryWithdrawals !(Map (RewardAcnt crypto) (CompactForm Coin)) because, in order to enact a proposal of this type, we need to be able to make refunds to stake credentials in the UMap, and there we store the compact version of coins, and, converting coins to their compact version is a partial operation.

If we do allow these proposals to use Coin instead, we find ourselves a problem of having to: either fail in enactment (which is impossible) or introduce yet another datatype to use the compacted version of Coin post GOV. This includes EnactState, GovState, etc.

Add lenses ensWithdrawalsL, ensTreasuryL and epochStateTreasuryL.

Derive the Num instance for CompactForm Coin.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-09-21 16:27 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Enact.hs
> +          , ensTreasury = ensTreasury st - wdrlsAmount -- TODO: This can be removed as it is an unused field
Let me know whether you think this is correct, so I will go ahead and remove this field.

2023-09-21 16:37 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +          & epochStateTreasuryL %~ (<> fromCompact (fold unsuccessfulRefunds - totalWithdrawals))
Note that here `totalWithdrawals >= unsuccessfulRefunds`

2023-09-21 17:53 UTC, aniketd commented
This needs a bit of rework (potential underflow and some known guarantees).

2023-09-22 07:47 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Enact.hs
> +          , ensTreasury = ensTreasury st - wdrlsAmount -- TODO: This can be removed as it is an unused field
This is wrong indeed.

2023-09-22 07:48 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +          & epochStateTreasuryL %~ (<> fromCompact (fold unsuccessfulRefunds - totalWithdrawals))
Wrong.

2023-09-22 12:56 UTC, lehins requested changes
You are still missing some parts from the spec, like this one:
https://github.com/input-output-hk/formal-ledger-specifications/blob/d8260e001e248725a01335253ce33f35d1656fe7/src/Ledger/Chain.lagda#L84

We'll talk more about it during the meeting, but I think you haven't looked deeply into how `ensTreasury` field works in EnactState and how it relates to `epochStateTreasuryL

2023-09-22 12:56 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +      -- we only reset the withdrawals here.
Both, the comment and implementation are wrong. 
ENACT state does not have access to the treasury

2023-09-22 12:56 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +          -- 2. the refunds and unsuccessful refunds together do not exceed the current treasury value
```suggestion
          -- 2. the refunds and unsuccessful refunds together do not exceed the current treasury value
          -- This is enforce by the `ENACT` rule
```

2023-09-22 12:56 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> +-- The subtraction of the `totWithdrawals` is already applied in ENACT
Same here. This is wrong
```suggestion
```

2023-09-22 16:07 UTC, aniketd commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs
> -        { esAccountState = acnt'
`acnt'` is already part of the `EpochState` a few lines above. And after that we update it in `applyEnactedWithdrawals` and so, it need not be updated here again.

2023-09-23 00:07 UTC, lehins approved these changes
Perfect! :+1:

2023-09-23 02:23 UTC, merged