Add checks for valid ProtVer when a proposal is a HardFork
IntersectMBO/cardano-ledger pull request #3888
Opened 2023-11-21 20:23 UTC by TimSheard

# Description
addresses issue #3873

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-11-22 00:01 UTC, lehins requested changes
There are some problems in the implementation.

@TimSheard I think this is a perfect ticket for you to get your hands dirty with ImpTest DSL. Could you please add a few unit tests into this module: 
[Test.Cardano.Ledger.Conway.Imp.GovSpec](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/impl/testlib/Test/Cardano/Ledger/Conway/Imp/GovSpec.hs)

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +      (GovActionId (EraCrypto era))
Firstly, this should have been `Maybe`, because the first proposal will contain Nothing, but we still need to check the version. Which is the first indicator that validation is not fully correct.
Secondly, we don't need to report the previous governance action id, because we already identify the proposal that contains it.
```suggestion
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +        else Just (ProposalCantFollow gaid1 protver1 gaid2 protver2)
GovActionId for current proposal was reported incorrectly. Also names with `1` and `2` don't give insight into which one is which
```suggestion
legalProtVer pp gas pgaids ps = do
  (newProtVer, prevProtVer) <- preceedingHardFork (gasAction gas) pp pgaids ps
  if pvCanFollow newProtVer (SJust prevProtVer)
    then Nothing
    else Just (gasId gas, (newProtVer, prevProtVer))
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +            _ -> Nothing
There are two problems here:
1. We do need to check the protocol version when previous governance action id is SNothing
2. previous governance action id of the previus governance action is not relevant for this check at all, but in current implementation it is require to be SJust, which would also cause the second HardForkInitiation ever proposed to not be validated.
```suggestion
  Maybe (ProtVer, ProtVer)
preceedingHardFork (HardForkInitiation mPrev newProtVer) pp pgaids ps
  | mPrev == pgaHardFork pgaids = Just (newProtVer, pp ^. ppProtocolVersionL)
  | otherwise = do
    SJust (PrevGovActionId prevGovActionId) <- Just mPrev
    HardForkInitiation _ prevProtVer <- gasAction <$> proposalsLookupId prevGovActionId ps
    Just (newProtVer, prevProtVer)
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +--   If it is not a HardFork, or the preceeding HardFork does not exist, return Nothing
```suggestion
-- | If the GovAction is a HardFork, then return 2 things (if they exist)
--   1) The proposed ProtVer
--   2) The ProtVer of that preceeding HardFork
--   If it is not a HardFork, or the previous govActionId points to something other 
-- than  HardFork, return Nothing. It will be verified with another predicate check
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +legalProtVer pp gas pgaids ps =
Type signature is too long and it will be more convenient for `proposalsHaveBadProtVer` to swap arguments:
```suggestion
legalProtVer :: EraPParams era => 
  PParams era ->
  PrevGovActionIds era -> 
  Proposals era -> 
  GovActionState era -> 
  Maybe (ConwayGovPredFailure era)
legalProtVer pp pgaids ps gas =
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +      Nothing -> Right ()
This approach will short circuit on the very first failure, which is not we normally do when validating transactions. We report all failures that we can find. Let's turn it into a Test. This will require a change to the predicate failure
```suggestion
proposalsHaveBadProtVer ::
     EraPParams era
  => PParams era
  -> PrevGovActionIds era
  -> Proposals era
  -> Test (ConwayGovPredFailure era)
proposalsHaveBadProtVer pp pgaids ps = 
  let invalidProposals = 
        mapMaybe (legalProtVer pp gas pgaids) $ toList (proposalsActions ps)
  in failureUnless (null invalidProposals) $ 
       ProposalsCantFollow (Map.fromList invalidProposals)
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +  | ProposalCantFollow
Let's make it contain a Map with all bad proposals that have this problem
```suggestion
  | ProposalsCantFollow
```

2023-11-22 00:01 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +{-# LANGUAGE BangPatterns #-}
No longer needed
```suggestion
```

2023-11-22 15:33 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +{-# LANGUAGE BangPatterns #-}
done

2023-11-22 15:33 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +  | ProposalCantFollow
done

2023-11-22 15:34 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +      (GovActionId (EraCrypto era))
done

2023-11-22 15:34 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +--   If it is not a HardFork, or the preceeding HardFork does not exist, return Nothing
done

2023-11-22 15:35 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +            _ -> Nothing
This was a misconception about what the GovActionID stood for,
done

2023-11-22 15:35 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +        else Just (ProposalCantFollow gaid1 protver1 gaid2 protver2)
done

2023-11-22 15:35 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +      Nothing -> Right ()
done

2023-11-22 15:35 UTC, TimSheard commented on eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Gov.hs
> +legalProtVer pp gas pgaids ps =
done

2023-11-27 16:41 UTC, lehins approved these changes
Beautiful. Thank you!

2023-11-27 23:47 UTC, merged