Ensure DRepRegistration certificate requires a witness
IntersectMBO/cardano-ledger pull request #3917
Opened 2023-12-07 12:30 UTC by TimSheard

Change 'getScriptWitnessConwayTxCert' so that DRepRegistration certificate requires a witness

Address #3890 
# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/input-output-hk/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/input-output-hk/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2023-12-07 14:47 UTC, lehins requested changes
We also need to change the `getVKeyWitnessConwayTxCert` that enforces the Key Witnesses

https://github.com/input-output-hk/cardano-ledger/blob/afedb7d519761ccdd9c013444aa4b3e0bf0e68ef/eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs#L642

2023-12-13 19:48 UTC, lehins approved these changes
:+1:

2023-12-13 19:48 UTC, merged

2023-12-18 00:56 UTC, james-iohk commented on eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs
>        -- Registration of a DRep does not require a witness
remove comment

2023-12-18 01:06 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs
>        -- Registration of a DRep does not require a witness
Thank. Done: https://github.com/IntersectMBO/cardano-ledger/pull/3934/commits/7796d194922649c686d8a9517ac329928f4245a7