Added SPO delegation injections to Conway
IntersectMBO/cardano-ledger pull request #3997
Opened 2024-01-18 13:21 UTC by Soupstraw

# Description

resolves #3995

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated
- [x] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [x] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [x] Self-reviewed the diff

2024-01-18 15:11 UTC, lehins requested changes
Unfortunately implementation for injection still has the same problem of requiring to load the whole input into memory, because it has to pass over the source ListMap twice.

I made a suggestion that should help you fix that.

2024-01-18 15:11 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +registerDelegs cfg = registerDRepDelegs cfg . registerStakeDelegs cfg
Unfortunately this is not gonna work, because this update has to happen in a single pass, not in two passes like it is implemented in this PR.

I suggest not using the views and instead modifying the Map in `umElems :: !(Map (Credential 'Staking c) (UMElem c))` directly. We don't need to worry about the invariant of keeping the `Ptr` map correct for this, since we are not going to have any pointer resolution in Conway, so it will be safe to manipulate the Map, instead of a the views.

2024-01-18 15:11 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs
> +        !> To dRep
There is a little too much noise when it is written like this. How about:
```suggestion
  encCBOR = encode . \case 
    DelegStake kh -> Sum DelegStake 0 !> To kh
    DelegVote dRep -> Sum DelegVote 1 !> To dRep
    DelegStakeVote kh dRep -> Sum DelegStakeVote 2 !> To kh !> To dRep
```

2024-01-19 12:45 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +registerDelegs cfg = registerDRepDelegs cfg . registerStakeDelegs cfg
I got rid of the functions that let you register DRep and stake pool delegations separately. We haven't released those yet so it should be fine to do so.

2024-01-19 13:14 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +registerDelegs cfg = registerDRepDelegs cfg . registerStakeDelegs cfg
Yeah, that's fine. They'll have to reintegrate those in consensus, but hat should not be a big deal.

2024-01-19 14:46 UTC, lehins requested changes
One more important issue and I think it is good to go.

2024-01-19 14:46 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +        (overrideSJust odrep ndrep)
That's just an alternative. Also don't be too stingy on descriptive names :wink: 
```suggestion
        (newStakePool <|> oldStakePool)
        (newDRep <|> oldDRrep)
```

2024-01-19 14:46 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +  , TranslationContext era ~ ConwayGenesis (EraCrypto era)
Why do you need this constraint?
```suggestion
```

2024-01-19 14:46 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +    delegs = cfg ^. tcTranslationContextL . cgDelegsL
Aha, this would bypass your `protectMainnetLens` protection that you wrote:
```suggestion
    delegs = cfg ^. tcDelegsL
```

2024-01-19 14:46 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
>      protectMainnetLens "DRepDelegs" null $
```suggestion
    protectMainnetLens "ConwayDelegs" null $
```

2024-01-19 14:46 UTC, lehins commented on libs/cardano-ledger-api/CHANGELOG.md
> +* Remove `registerDRepDelegs`
Just modify the original entry below:
```diff
-* Add `registerInitialDReps`, `registerDRepDelegs`
+* Add `registerInitialDReps`, `registerDelegs`
```
```suggestion
```

2024-01-19 14:46 UTC, lehins commented on eras/conway/impl/CHANGELOG.md
> +* Remove `registerDRepDelegs`
Same here. It is the same version and previous addition hasn't been released yet
```suggestion
```
```diff
-* Add `registerInitialDReps` and `registerDRepDelegs`
+* Add `registerInitialDReps` and `registerDelegs`
```

Also change this line:
```diff
-* Add `cgDRepDelegs`, `cgInitialDReps` to `ConwayGenesis`
+* Add `cgDelegs`, `cgInitialDReps` to `ConwayGenesis`
```

2024-01-22 10:59 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +        (overrideSJust odrep ndrep)
I thought so as well at first, but it's not. Alternative takes the first `SJust` it sees and sticks with that, while `overrideSJust` takes the second argument when both are `SJust`.

2024-01-22 11:00 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +  , TranslationContext era ~ ConwayGenesis (EraCrypto era)
Because of `cgDelegsL`

2024-01-22 11:03 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +        (overrideSJust odrep ndrep)
oh, right I see now that you flipped the arguments.

2024-01-22 11:09 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +  , TranslationContext era ~ ConwayGenesis (EraCrypto era)
This is fixed by your other suggestion

2024-01-22 11:10 UTC, Soupstraw commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +    delegs = cfg ^. tcTranslationContextL . cgDelegsL
Good catch!

2024-01-22 12:42 UTC, lehins approved these changes
Beautiful!

2024-01-22 13:16 UTC, merged