Add a new function `registerInState` to `EraTransition`
IntersectMBO/cardano-ledger pull request #4023
Opened 2024-01-29 17:11 UTC by dnadales

... which allows to inject transition configuration data in the given `NewEpochState`.

This change allows the Ledger to define this logic in this component without needing to do it in the Consensus layer. In this way, we improve the separation of concerns.

Part of https://github.com/IntersectMBO/ouroboros-consensus/issues/899

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated. **If you change the bounds in a cabal file, that package itself must have a version increase.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages. **New section is never added with the code changes.** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2024-01-30 11:12 UTC, amesgen commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
This PR could also remove the `ConwayEraTransition` class as it won't be used by Consensus anymore after this PR.

2024-01-30 11:12 UTC, amesgen commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> +    NewEpochState era
I think the name could mention a keyword like "testing" or "nonMainnet" to emphasize that this functionality is not relevant (or rather, will even throw an imprecise exception) for mainnet.

2024-01-30 11:12 UTC, amesgen commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
In Consensus, we don't directly use this modules, but rather the re-exports from `Cardano.Ledger.Api.Transition`. I think it makes to remove all the "fine-grained" registration functions (like `registerInitialFunds`) there and instead only export `registerInState` (or whatever name we end up choosing).

2024-01-30 14:23 UTC, lehins reviewed
Looks good so far. These changes totally make sense and I also agree with @amesgen comments.

2024-01-30 14:23 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> +    NewEpochState era
How about `injectTestState`?

> will even throw an imprecise exception) for mainnet.

Also describing this in the haddock would be good.

2024-01-30 14:23 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
>  I think it makes to remove all the "fine-grained" registration

Yes, we can stop exporting them from this module:

@amesgen What about `createInitialState` and `registerInitialStaking` in here: https://github.com/IntersectMBO/ouroboros-consensus/blob/63fa2385a360eff10208c09f8ec055a13dae1984/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/TPraos.hs#L345-L346

Do you still need them?

2024-01-30 14:44 UTC, amesgen commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> What about `createInitialState` and `registerInitialStaking` in here: https://github.com/IntersectMBO/ouroboros-consensus/blob/63fa2385a360eff10208c09f8ec055a13dae1984/ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/TPraos.hs#L345-L346
> 
> Do you still need them?

We hope to find this out later today :smile:

2024-01-30 15:01 UTC, dnadales commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> +    NewEpochState era
I'll add some haddock :fish: As for the name, mentioning "test" in the name makes sense. I don't know if we want to modify it slightly to reflect that it is injecting into the state, so, for instance, `injectIntoTestState`. What do you think?

2024-01-30 15:09 UTC, dnadales commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> +    NewEpochState era
I could copy the comments of the other functions. We might remove them or make them shorter if said functions are not exposed anymore.

```
    -- /Warning/ - Should only be used in testing and benchmarking. Will result in an error
    -- when 'NetworkId' is set to 'Mainnet'.
```

2024-01-30 15:33 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> +    NewEpochState era
> reflect that it is injecting into the state, so, for instance, injectIntoTestState.

Sounds good with me, if you prefer that name instead

2024-01-30 17:43 UTC, dnadales commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +  (era ~ ConwayEra c, Crypto c) =>
TODO: I should remove the type equality as well. I missed this :/

2024-01-31 09:46 UTC, amesgen commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
FTR: We looked at that code in `TPraos`, and figured that we only need `createInitialState` and `injectIntoTestState`, but not `registerInitialStaking` or other fine-grained functions.

However, we need to change `createInitialState` to not register the initial funds; otherwise, `injectIntoTestState` fails to register the initial funds as they are already there :smile: See 77f8f22127e7ad5e2bb9e3a98bc53406dbe76fea.

2024-01-31 09:53 UTC, amesgen commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +  Lens' (TransitionConfig (ConwayEra c)) (ConwayGenesis (EraCrypto (ConwayEra c)))
```suggestion
  Lens' (TransitionConfig (ConwayEra c)) (ConwayGenesis c)
```

2024-01-31 10:33 UTC, dnadales commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> +  Lens' (TransitionConfig (ConwayEra c)) (ConwayGenesis (EraCrypto (ConwayEra c)))
Good catch! Thanks!

2024-01-31 10:40 UTC, dnadales commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
Done. Thanks!

2024-01-31 11:05 UTC, amesgen commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
FTR: The `ConwayEraTransition` class is actually necessary such that post-Conway eras can register the stuff that is new since Conway. I didn't think of that while writing this comment.

2024-01-31 12:50 UTC, lehins requested changes
PR looks great. Just some changelog entries and version+bounds adjustments.

2024-01-31 12:50 UTC, lehins commented on eras/conway/impl/src/Cardano/Ledger/Conway/Transition.hs
> -  registerInitialDReps,
Could you please add an entry to the changelog (for the latest version) that these functions have been removed

2024-01-31 12:50 UTC, lehins commented on eras/shelley/impl/src/Cardano/Ledger/Shelley/Transition.hs
> +  registerInitialFundsThenStaking,
These changes and addition of `injectIntoTestState` should definitely be listed in the changelog. Version needs to be bumped as well to `1.10.0.0` in the cabal (`1.9.0.0` -> `1.10.0.0`) file and the changelog (`1.9.0.1` -> `1.10.0.0`).

This will require some bounds to be adjusted in other packages in the ledger repo:

* All era packages and the api will need a lower bound updated (due to dependency on the new `injectIntoTestState`)
* while any other package in the ledger repo will just need an upper bound relaxed.

2024-01-31 12:50 UTC, lehins commented on libs/cardano-ledger-api/src/Cardano/Ledger/Api/Transition.hs
> +  injectIntoTestState,
These changes should be listed in the changelog as well. No need to update the version since that has already been done in a recent PR.

2024-01-31 17:18 UTC, dnadales commented on libs/cardano-ledger-api/src/Cardano/Ledger/Api/Transition.hs
> +  injectIntoTestState,
Also mention that we updated the semantics of `createInitialState`.

2024-01-31 17:23 UTC, lehins approved these changes
Thank you!! This looks great.
Makes me happy to see improvements to this interface

2024-01-31 20:13 UTC, merged