Bump Plutus deps to 1.22.0.0
IntersectMBO/cardano-ledger pull request #4111
Opened 2024-02-22 18:20 UTC by Unisay

This PR updates Plutus dependencies versions to 1.22.0.0

Related: https://github.com/IntersectMBO/cardano-haskell-packages/pull/669

2024-02-22 19:08 UTC, lehins approved these changes
LGTM. Thanks.

2024-02-22 19:09 UTC, lehins requested changes
Ah. Didn't look at the CI. 
Looks like there are some breaking changes in plutus 1.22 that need to be accounted for

2024-02-23 10:43 UTC, Unisay commented
I am closing this PR as I am going to release a minor version of the plutus dependencies which will use `V3.TxId` consistently across the `V3.ScriptContext`

2024-02-23 10:43 UTC, closed without merging

2024-02-23 10:55 UTC, lehins commented
> I am going to release a minor version of the plutus dependencies which will use V3.TxId consistently across the V3.ScriptContext

I would expect this to be a breaking change according to PVP, but I am not sure what sort of versioning policy was adopted in plutus repo