Remove `minMajorPV` and `maxMajorPV` from `Constants`
IntersectMBO/cardano-ledger pull request #4576
Opened 2024-08-28 03:29 UTC by lehins

# Description

We no longer need ot specify the corret protocol version values for a specific era, we have this  information available at the type level.

Moreover it was totally wrong to generate protocol version values for PParamsUpdate too far into the future of a particular era, eg. major protocol version 9 makes no sense in Shelley era.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2024-08-28 14:01 UTC, Lucsanszky requested changes
Some hiccups with the version numbers (but please definitely double check in case I'm wrong). Other than that: LGTM :+1:

2024-08-28 14:01 UTC, Lucsanszky commented on eras/alonzo/impl/cardano-ledger-alonzo.cabal
I think you will have to bump the patch version here. There are some more and unfortunately, GitHub doesn't allow adding suggestions there since they are "out of range", so I'll just mark them.

2024-08-28 14:01 UTC, Lucsanszky commented on eras/alonzo/test-suite/cardano-ledger-alonzo-test.cabal
Needs a patch version bump.

2024-08-28 14:01 UTC, Lucsanszky commented on eras/conway/impl/cardano-ledger-conway.cabal
> +version:            1.16.2.1
```suggestion
```

Hmm, to me it seems like `cardano-ledger-conway-1.16.2.0` hasn't been released yet, so no need to bump.

2024-08-28 14:01 UTC, Lucsanszky commented on eras/shelley-ma/test-suite/cardano-ledger-shelley-ma-test.cabal
> +version:       1.2.2.4
:+1:, however it seems like that we are missing a tag for `cardano-ledger-shelley-ma-test-1.2.2.3`, so I'll push the tag ASAP.

2024-08-28 14:01 UTC, Lucsanszky commented on eras/shelley/test-suite/cardano-ledger-shelley-test.cabal
> +version:            1.4.1.0
`CHANGELOG.md` for `shelley/test-suite` will need to be updated too.

2024-08-28 14:01 UTC, Lucsanszky commented on libs/cardano-ledger-api/cardano-ledger-api.cabal
> +version:            1.9.4.1
```suggestion
```

`cardano-ledger-api-1.9.4.0` hasn't been released yet, so no need to bump any further.

2024-08-28 19:11 UTC, lehins commented on eras/alonzo/impl/cardano-ledger-alonzo.cabal
I thought I got them all. Thank you for catching it.

2024-08-28 19:12 UTC, lehins commented on eras/conway/impl/cardano-ledger-conway.cabal
> +version:            1.16.2.1
Good catch!

2024-08-28 19:12 UTC, lehins commented on eras/alonzo/test-suite/cardano-ledger-alonzo-test.cabal
Ditto

2024-08-28 19:13 UTC, lehins commented on eras/shelley/test-suite/cardano-ledger-shelley-test.cabal
> +version:            1.4.1.0
Done

2024-08-28 19:14 UTC, lehins commented on libs/cardano-ledger-api/cardano-ledger-api.cabal
> +version:            1.9.4.1
Fixed

2024-08-28 19:19 UTC, lehins commented on eras/shelley-ma/test-suite/cardano-ledger-shelley-ma-test.cabal
> +version:       1.2.2.4
I've added a tag: https://github.com/IntersectMBO/cardano-ledger/tree/cardano-ledger-shelley-ma-test-1.2.2.3

Thank you for catching this too!

2024-08-28 20:07 UTC, Lucsanszky approved these changes

2024-08-28 20:46 UTC, lehins commented
@Lucsanszky Thank you for catching all these issues. This only further strengthens my desire to create a tool that enforces all these checks on CI: https://github.com/IntersectMBO/cardano-ledger/issues/4583

2024-08-28 23:12 UTC, merged

2024-08-29 02:57 UTC, Lucsanszky commented
> @Lucsanszky Thank you for catching all these issues. This only further strengthens my desire to create a tool that enforces all these checks on CI: #4583

I was thinking exactly the same. Cheers for opening an issue for it!