fix both reproduceable failures
IntersectMBO/cardano-ledger pull request #4596
Opened 2024-09-03 22:11 UTC by TimSheard

Addresses issue 4588

Needs some cleanup

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ ] Self-reviewed the diff

2024-09-04 21:04 UTC, lehins requested changes
Do they have an `Ord` instance? If they do, I'd highly recommend using `nubOrd` instead. We have an implementation of it here, so you can just import it:

https://github.com/IntersectMBO/cardano-ledger/blob/c55f7ca2848d78c029bf182777854af5b71e9562/eras/mary/impl/src/Cardano/Ledger/Mary/Value.hs#L761


The reason for this is `nub` is O(n^2) complexity and is ridiculously slow. We don't want our generators to be even slower then they already are.

*This suggestion goes for all uses of `nub` in this PR*

2024-09-04 21:04 UTC, lehins commented on libs/constrained-generators/src/Constrained/Base.hs
> +conformsToSpecM _ (ErrorSpec es) = fatalError (NE.fromList ("conformsToSpecM ErrorSpec case" : NE.toList es))
There is a cons operator for NonEmpty:
```suggestion
conformsToSpecM _ (ErrorSpec es) = fatalError ("conformsToSpecM ErrorSpec case" NE.<| es)
```

2024-09-04 21:04 UTC, lehins commented on libs/constrained-generators/src/Constrained/Base.hs
> +    let szSpec' = (szSpec <> geqSpec @fn (sizeOf must) <> maxSpec (cardinality elemS))
```suggestion
    let szSpec' = szSpec <> geqSpec @fn (sizeOf must) <> maxSpec (cardinality elemS)
```

2024-09-04 21:04 UTC, lehins commented on libs/constrained-generators/src/Constrained/Base.hs
> +    choices <- pureGen $ shuffle (xs \\ (Set.toList must))
```suggestion
    choices <- pureGen $ shuffle (xs \\ Set.toList must)
```

2024-09-04 21:04 UTC, lehins commented on libs/constrained-generators/src/Constrained/GenT.hs
> +-- import Control.Applicative
```suggestion
```

2024-09-05 11:16 UTC, TimSheard commented
So some thoughts about the use of nub.
One of the failures was caused by duplicates in 'xs' in (MemberSpec xs). The nub fixed it.
Further investigation showed, there were lots of duplicates in MemberSpec.
Using nub actually made the code run faster, because the majority of time is spent generating random instances, and the duplicates made this smaller. The time spent simplifying Specifications (where we use the nub) is a small fraction of the total time. The most common MemberSpec has one or two elements.
Almost all  large MemberSpecs arise from big Sets, but in those cases we construct the MemberSpec as follows (MemberSpec (Set.toList set)) where we don't need to use nub. 

Finally in every case where we used nub (I checked this carefully) all we have is a (HasSpec fn a) this implies (Eq a) but not (Ord a).  So there is nothing to do.

2024-09-05 17:15 UTC, lehins approved these changes
Thank you!!!!

2024-09-05 19:26 UTC, merged