Align with Governance audit
IntersectMBO/cardano-ledger pull request #4656
Opened 2024-10-01 02:08 UTC by Ranchhand87

# Description

Edits to CODE-OF-CONDUCT.md 
Text edit in SECURITY.md
Adding Issue Templates

Please review changes carefully. Please ensure Discussions are enabled prior to merging. Contact @Ranchhand87 if assistance in needed to enable Discussions. 

# Checklist

- [ y ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-ledger/blob/master/RELEASING.md#versioning-process))
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) (use `scripts/fourmolize.sh`)
- [x] Cabal files are formatted (use `scripts/cabal-format.sh`)
- [x] [`hie.yaml`](https://github.com/intersectmbo/cardano-ledger/blob/master/hie.yaml) has been updated (use `scripts/gen-hie.sh`)
- [ y ] Self-reviewed the diff

2024-10-01 16:00 UTC, lehins requested changes
There are some issues with an issue template. As I was saying earlier, we don't really need an issue template for the Ledger repo. But, if you insist on us having it, then we either need totally different sections or current suctions need to be removed.

It is not a simple the "what" and a "how" in ledger. There are a lot more nuances, that only Ledger maintainers can answerr: eg. does it require a hard fork, if so can it be changed with an intra-era hard fork, does it require changes to CDDL, serialization of ledger state, ...

So, my question to you is this template targets ledger maintainers or downstream users that request features and report bugs?

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/config.yml
> +    url: https://github.com/cardano-ledger/blob/master/CONTRIBUTING.md
```suggestion
    url: https://github.com/IntersectMBO/cardano-ledger/blob/master/CONTRIBUTING.md
```

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/config.yml
> +    url: https://github.com/cardano-ledger/discussions/categories/ideas
```suggestion
    url: https://github.com/IntersectMBO/cardano-ledger/discussions/categories/ideas
```

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/config.yml
> +    url: https://github.com/cardano-ledger/issues
```suggestion
    url: https://github.com/IntersectMBO/cardano-ledger/issues
```

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/feature_idea_ledger.yml
> +        That way, we can discuss & refine your idea together, before we adopt it as a feature into the roadmap.
Why are we starting to use these "ideas"? Don't we already have a CIP process for that?

I am not really opposing this, but I do want to know when we should use one vs the other. We need to clarify this in the template as well.

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/feature_idea_ledger.yml
> +        a new configuration option, ...
We don't have messaging, API endpoints or configuration options.

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/feature_idea_ledger.yml
> +        components need to change, steps how to implement this, ...
It is unlikely that people who are not involved in ledger codebase maintenance will know how a problem has to be solved from the technical point of view. If an issue is created by ledger maintainers then we already know what needs to be written in the ticket
```suggestion
```

2024-10-01 16:00 UTC, lehins commented on .github/ISSUE TEMPLATE/feature_idea_ledger.yml
> +        Give context and describe the problem, challenge or opportunity you see
I think this is the only sensible section for the Ledger project in this template. I would suggest removing all others.

2024-10-01 16:00 UTC, lehins commented on CODE-OF-CONDUCT.md
> +.
Dot is on a newline. Also feels like `at` is out of place and the sentence is not fully finished "responsible for enforcement ... " of what?
```suggestion
reported to the community leaders responsible for enforcement at.

```

2024-10-04 04:22 UTC, Ranchhand87 commented on .github/ISSUE TEMPLATE/feature_idea_ledger.yml
> +        Give context and describe the problem, challenge or opportunity you see
@lehins Committed suggestions. Rewrote Issue temp to be more general for the time being, at least at a place where you and the team can add to it in the future when there is time. Also removed Discussions from the Config. We can revisit that topic separately and consider re-adding at a later date. Hoping this helps.

2024-10-04 04:29 UTC, lehins approved these changes
Looks good. Thank you!

2024-10-17 18:32 UTC, lehins approved these changes

2024-10-17 18:32 UTC, lehins commented on .github/ISSUE TEMPLATE/config.yml
> +    about: Check whether your issue is not already covered here.
```suggestion
    about: Check whether your issue is not already covered here.

```

2024-10-17 18:32 UTC, lehins commented on .github/ISSUE TEMPLATE/feature_idea_ledger.yml
> +(For maintainers: add relevant labels such as `bug`, `enhancement`, `technical-debt`, etc.)
```suggestion
(For maintainers: add relevant labels such as `bug`, `enhancement`, `technical-debt`, etc.)

```

2024-10-17 21:25 UTC, merged